<?php
/** File 08 eighth fresh ten-round corrective regression gate. */
$root = dirname( __DIR__ ); $failures=array(); $checks=0;
function t810src($p){global $root,$failures;$f=$root.'/'.$p;if(!is_file($f)){$failures[]='Missing '.$p;return '';} $s=file_get_contents($f);return is_string($s)?$s:'';}
function t810has($l,$s,$n){global $failures,$checks;$checks++;if(false===strpos($s,$n)){$failures[]=$l.' missing: '.$n;}}
function t810lacks($l,$s,$n){global $failures,$checks;$checks++;if(false!==strpos($s,$n)){$failures[]=$l.' forbidden: '.$n;}}
$bootstrap=t810src('worldwide-clinic.php'); $contracts=t810src('includes/class-wca-contracts.php'); $service=t810src('includes/class-wca-service.php'); $guard=t810src('includes/class-wca-plan-guard.php'); $continuity=t810src('includes/class-wca-continuity-secure.php'); $future=t810src('includes/class-wca-future24.php'); $reconcile=t810src('includes/class-wca-verification-reconciliation.php'); $staging=t810src('STAGING-ACCEPTANCE.md');
t810lacks('doctor suspension has no artificial 500-page ceiling',$service,'&& $page <= 500');
t810has('doctor suspension complete terminal page',$service,'while ( 200 === count( $appointments ) )');
t810lacks('verification reconciliation has no artificial 100-page ceiling',$reconcile,'&& $page <= 100');
t810has('continuity reminder keyset cursor',$continuity,'AND id>%d'); t810has('continuity reminder transaction',$continuity,'START TRANSACTION'); t810has('continuity reminder row lock',$continuity,'FOR UPDATE'); t810has('continuity reminder rollback',$continuity,'ROLLBACK'); t810has('continuity reminder CAS',$continuity,'version=version+1');
t810has('canonical payload key overflow',$future,'wca_future24_payload_keys'); t810has('canonical payload item overflow',$future,'wca_future24_payload_items'); t810has('strict operational payload writer',$future,'sanitize_operational_payload( $payload, $strict = false )');
t810has('practitioner ref advisory lock',$guard,'SELECT GET_LOCK(%s,3)'); t810has('practitioner ref lock release',$guard,'SELECT RELEASE_LOCK(%s)');
t810has('slot display date lower bound',$service,'display_date_from'); t810has('slot display date upper bound',$service,'display_date_to'); t810has('exact held slot projector',$service,'project_rule_slot'); t810has('hold uses exact rule projector',$guard,'WCA_Service::project_rule_slot'); t810has('hold replay repository key',$guard,'$repository_key');
t810has('waitlist semantic lock',$future,"semantic_lock( 'waitlist'"); t810has('window semantic lock',$future,"semantic_lock( 'windows'"); t810has('support participant semantic lock',$future,"semantic_lock('support-participant'"); t810has('support participant transaction',$future,'START TRANSACTION'); t810has('support participant File17 projection',$future,'File17.AppointmentParticipantChanged.v1'); t810has('support participant commit',$future,'COMMIT');
t810has('plugin 1.2.8',$bootstrap,'Version: 1.2.8'); t810has('runtime 1.2.8',$contracts,"RUNTIME_VERSION                 = '1.2.8'"); t810has('core schema 3.2.0',$contracts,"SCHEMA_VERSION                  = '3.2.0'"); t810has('staging schema parity',$staging,'File 08 core schema `3.2.0`'); t810has('zero commission',$contracts,"'commission_percent' => 0"); t810has('no automated diagnosis',$contracts,"'automated_diagnosis' => false"); t810has('no automated prescribing',$contracts,"'automated_prescribing' => false");
$runtime=implode("\n",array($bootstrap,$contracts,$service,$guard,$continuity,$future,$reconcile)); foreach(array('eval(','base64_decode(','shell_exec(','unserialize(') as $t){t810lacks('forbidden runtime primitive',$runtime,$t);} if($failures){fwrite(STDERR,"File 08 eighth-ten-review regression gate failed:\n- ".implode("\n- ",$failures)."\n");exit(1);} echo 'File 08 eighth fresh ten-round regression assertions passed: '.$checks.'/'.$checks.".\n";
