<?php
/** File 08 eleventh fresh twenty-round corrective regression gate. */
$root=dirname(__DIR__); $failures=array(); $checks=0;
function e11src($p){global $root,$failures;$f=$root.'/'.$p;if(!is_file($f)){$failures[]='Missing '.$p;return '';} $s=file_get_contents($f);return is_string($s)?$s:'';}
function e11has($l,$s,$n){global $failures,$checks;$checks++;if(false===strpos($s,$n)){$failures[]=$l.' missing: '.$n;}}
function e11lacks($l,$s,$n){global $failures,$checks;$checks++;if(false!==strpos($s,$n)){$failures[]=$l.' forbidden: '.$n;}}
$boot=e11src('worldwide-clinic.php');$contracts=e11src('includes/class-wca-contracts.php');$repo=e11src('includes/class-wca-repository.php');$service=e11src('includes/class-wca-service.php');$helpers=e11src('includes/class-swc-helpers.php');$outbox=e11src('includes/class-wca-outbox.php');$rest=e11src('includes/class-wca-rest.php');$future=e11src('includes/class-wca-future24.php');
foreach(array('$started = $wpdb->query( \'START TRANSACTION\' )','$committed = $wpdb->query( \'COMMIT\' )','_commit') as $n){e11has('repository transaction control',$repo,$n);}foreach(array('swc_transaction_start_failed','swc_transaction_commit_failed') as $n){e11has('appointment transaction control',$helpers,$n);}e11has('stale lock compare-and-swap',$helpers,'option_value=%s WHERE option_name=%s AND option_value=%s');e11lacks('stale lock delete-before-acquire',$helpers,'delete_option( $key );'."\n\t\t\t\t".'add_option');
e11has('worker-fenced complete',$repo,'complete_outbox( $id, $worker');e11has('worker-fenced failure',$repo,'fail_outbox( $id, $error, $attempts, $worker');e11has('dispatcher completion check',$outbox,'durable worker-fenced finalization failed');e11has('dispatcher finalization contention',$outbox,'outbox_finalize_contention_total');e11has('all-recipient fallback',$outbox,'$all_sent = true');e11lacks('partial-recipient success',$outbox,'$sent = wp_mail');
e11has('appointment replay key bounds',$service,"preg_match( '/^[A-Za-z0-9._:-]{8,128}$/', " . '$idempotency_key' . ' )');e11has('patient timezone fail closed',$service,'wca_patient_timezone_invalid');e11has('slot from date fail closed',$service,'wca_slot_date_from_invalid');e11has('slot to date fail closed',$service,'wca_slot_date_to_invalid');e11has('inside-lock authorization recheck',$service,'$current_auth = WCA_Authorization::can_transition_appointment');e11has('actual mode validation',$service,'wca_actual_mode_invalid');
e11has('opaque clinic appointment DTO',$rest,"'clinic_ref'");e11has('opaque service appointment DTO',$rest,"'service_ref'");e11has('protected mutation allowlist',$rest,'protected_mutation_projection');e11lacks('appointment DTO native clinic id',$rest,"'clinic_id'         => absint( SWC_Helpers::meta");e11lacks('appointment DTO native service id',$rest,"'service_id'        => absint( SWC_Helpers::meta");e11has('doctor suspension atomic reconciliation',$service,'wca_doctor_suspension_reconcile_transaction');e11has('doctor suspension failure evidence',$service,'doctor_suspension_reconcile_failed');e11has('service type validation',$service,'wca_service_consultation_type');e11has('service currency validation',$service,'wca_service_currency');e11has('repository branch timezone validation',$repo,'wca_repository_branch_timezone');e11has('repository service currency validation',$repo,'wca_repository_service_currency');e11has('repository service type validation',$repo,'wca_repository_service_type');e11has('repository availability timezone validation',$repo,'wca_repository_availability_timezone');e11has('plugin 1.2.11',$boot,'Version: 1.2.11');e11has('runtime 1.2.11',$contracts,"RUNTIME_VERSION                 = '1.2.11'");e11has('schema stays 3.2.0',$contracts,"SCHEMA_VERSION                  = '3.2.0'");e11has('idempotency completion CAS',$repo,'array( \'id\' => absint( $id ), \'status\' => \'processing\' )');e11has('idempotency completion row count',$repo,'return 1 === (int) $updated;');e11has('Future24 completion checked',$future,'$completed = WCA_Repository::complete_idempotency');e11has('Future24 reconciliation failure',$future,'wca_idempotency_finalize_failed');
$runtime=implode("\n",array($boot,$contracts,$repo,$service,$helpers,$outbox,$rest));foreach(array('eval(','base64_decode(','shell_exec(','unserialize(') as $n){e11lacks('forbidden runtime primitive',$runtime,$n);}if($failures){fwrite(STDERR,"File 08 eleventh twenty-round regression gate failed:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo 'File 08 eleventh fresh twenty-round regression assertions passed: '.$checks.'/'.$checks.".\n";
