<?php
/** File 08 ninth fresh ten-round corrective regression gate. */
$root=dirname(__DIR__); $failures=array(); $checks=0;
function n9src($p){global $root,$failures;$f=$root.'/'.$p;if(!is_file($f)){$failures[]='Missing '.$p;return '';} $s=file_get_contents($f);return is_string($s)?$s:'';}
function n9has($l,$s,$n){global $failures,$checks;$checks++;if(false===strpos($s,$n)){$failures[]=$l.' missing: '.$n;}}
function n9lacks($l,$s,$n){global $failures,$checks;$checks++;if(false!==strpos($s,$n)){$failures[]=$l.' forbidden: '.$n;}}
$boot=n9src('worldwide-clinic.php'); $contracts=n9src('includes/class-wca-contracts.php'); $helpers=n9src('includes/class-swc-helpers.php'); $front=n9src('includes/class-swc-frontend.php'); $appointments=n9src('includes/class-swc-appointments.php'); $admin=n9src('includes/class-swc-admin.php'); $service=n9src('includes/class-wca-service.php'); $future=n9src('includes/class-wca-future24.php');
n9has('browser uses opaque doctor field',$front,'name="doctor_ref"'); n9lacks('browser hides numeric doctor field',$front,'name="doctor_id" required'); n9has('opaque doctor resolver',$appointments,'SWC_Helpers::practitioner_id( $doctor_ref )');
n9has('submit direct eligibility',$appointments,'SWC_Helpers::doctor_is_requestable( $doctor )'); n9has('reassignment direct eligibility',$appointments,'SWC_Helpers::doctor_is_requestable( $new_doctor )'); n9has('admin direct eligibility',$admin,'SWC_Helpers::doctor_is_requestable( $doctor )');
n9has('appointment DB transaction',$helpers,'with_database_transaction'); n9has('transaction rollback',$helpers,"query( 'ROLLBACK' )"); n9has('postmeta cache invalidation',$helpers,'wp_cache_delete(');
n9has('transition event checked',$service,'event_record = WCA_Repository::append_event'); n9has('transition outbox checked',$service,'outbox_event = WCA_Repository::enqueue'); n9has('transition notification checked',$service,'notification = WCA_Repository::enqueue'); n9has('transition communication checked',$service,'communication = WCA_Repository::enqueue'); n9has('completion eligibility fail closed',$service,'if ( is_wp_error( $eligibility ) ) { return $eligibility; }'); n9has('transition audit fail closed',$service,'wca_transition_audit');
n9has('future record id captured',$future,'record_id = (int) $wpdb->insert_id;'); n9has('future audit unavailable error',$future,'wca_future24_audit_unavailable'); n9has('future audit returns event result',$future,"return WCA_Repository::append_event( 'Future24GovernanceRecorded.v1'");
n9has('waitlist offer semantic lock',$future,"semantic_lock( 'waitlist-offer'"); n9has('waitlist enqueue checked',$future,'if ( is_wp_error( $queued ) )');
n9has('participant revoke semantic lock',$future,"semantic_lock( 'support-participant-revoke'"); n9has('participant revoke version CAS',$future,'AND version=%d');
n9has('virtual room semantic lock',$future,"semantic_lock('virtual-room'"); n9has('virtual room canonical transaction',$future,'wca_virtual_room_transaction');
n9has('group cancellation member failure',$future,'wca_group_member_cancel_failed'); n9has('group cancellation audit checked',$future,'if ( is_wp_error( $audit ) )');
n9has('plugin 1.2.11',$boot,'Version: 1.2.11'); n9has('runtime 1.2.11',$contracts,"RUNTIME_VERSION                 = '1.2.11'"); n9has('schema remains 3.2.0',$contracts,"SCHEMA_VERSION                  = '3.2.0'");
$runtime=implode("\n",array($boot,$contracts,$helpers,$front,$appointments,$admin,$service,$future)); foreach(array('eval(','base64_decode(','shell_exec(','unserialize(') as $t){n9lacks('forbidden runtime primitive',$runtime,$t);} if($failures){fwrite(STDERR,"File 08 ninth-ten-review regression gate failed:\n- ".implode("\n- ",$failures)."\n");exit(1);} echo 'File 08 ninth fresh ten-round regression assertions passed: '.$checks.'/'.$checks.".\n";
