<?php
$root=dirname(__DIR__); $pass=0; $fail=array();
function t16h($label,$path,$needle){global $root,$pass,$fail;$s=file_get_contents($root.'/'.$path);if(is_string($s)&&false!==strpos($s,$needle)){echo 'PASS '.(++$pass).': '.$label."\n";}else{$fail[]=$label.' missing: '.$needle;}}
function t16n($label,$path,$needle){global $root,$pass,$fail;$s=file_get_contents($root.'/'.$path);if(is_string($s)&&false===strpos($s,$needle)){echo 'PASS '.(++$pass).': '.$label."\n";}else{$fail[]=$label.' forbidden needle present: '.$needle;}}
function t16order($label,$path,$first,$second){global $root,$pass,$fail;$s=file_get_contents($root.'/'.$path);$a=is_string($s)?strpos($s,$first):false;$b=is_string($s)?strpos($s,$second):false;if(false!==$a&&false!==$b&&$a<$b){echo 'PASS '.(++$pass).': '.$label."\n";}else{$fail[]=$label.' order invariant failed';}}

t16h('R1 continuity batch read fails closed','includes/class-wca-continuity-secure.php','null === $rows_raw && \'\' !== (string) $wpdb->last_error');
t16h('R1 continuity zero-delete readback fails closed','includes/class-wca-continuity-secure.php','null === $still_exists && \'\' !== (string) $wpdb->last_error');
t16h('R1 continuity completion read fails closed','includes/class-wca-continuity-secure.php','null === $more && \'\' !== (string) $wpdb->last_error');
t16h('R1 continuity guardian readback fails closed','includes/class-wca-continuity-secure.php','null === $guardian_remaining && \'\' !== (string) $wpdb->last_error');
t16h('R1 Future24 table probe fails closed','includes/class-wca-privacy.php','wca_privacy_future24_table_read_failed');
t16h('R1 privacy export propagates Future24 table failure','includes/class-wca-privacy.php','if ( is_wp_error( $table ) ) { return $table; }');
t16h('R1 strict audit history read exists','includes/class-swc-helpers.php','public static function audit_rows_strict');
t16h('R1 privacy export uses strict audit read','includes/class-swc-privacy.php','SWC_Helpers::audit_rows_strict');
t16h('R1 review eligibility duplicate read fails closed','includes/class-wca-repository.php','wca_review_eligibility_read_failed');
t16h('R4 continuity routes join HTTP idempotency guard','includes/class-wca-ten-review-hardening.php','continuity/appointments/[0-9a-fA-F-]{36}');
t16h('R4 continuity completion joins HTTP idempotency guard','includes/class-wca-ten-review-hardening.php','continuity/followups/[0-9a-fA-F-]{36}/complete');
t16h('R4 Future24 retains its own mutation guard','includes/class-wca-ten-review-hardening.php','strpos( $route, \'/wca/v1/future24/\' )');
t16h('R4 intake version guard runs after replay guard','includes/class-wca-continuity-guards.php',"enforce_intake_version' ), 20, 3");
t16h('R4 browser continuity sends idempotency header','assets/js/continuity.js',"'Idempotency-Key'");
t16h('R4 browser continuity persists ambiguous mutation key','assets/js/continuity.js','sessionStorage.setItem');
t16h('R4 browser mutation key uses secure randomness','assets/js/continuity.js','window.crypto.randomUUID');
t16h('R6 outbox claim write failure explicit','includes/class-wca-repository.php','wca_outbox_claim_write_failed');
t16h('R6 outbox successful claim requires readback','includes/class-wca-repository.php','wca_outbox_claim_readback_missing');
t16h('R6 ambiguous WP error retains reconciliation evidence','includes/class-wca-ten-review-hardening.php','http_idempotency_ambiguous_error_total');
t16h('R6 ambiguous response advertises reconciliation','includes/class-wca-ten-review-hardening.php','X-WCA-Reconciliation-Required');
t16h('R6 unverifiable response fails closed','includes/class-wca-ten-review-hardening.php','wca_idempotency_response_unverifiable');
t16h('R6 idempotency release DB failure observable','includes/class-wca-repository.php','idempotency_release_db_failed_total');
t16h('R6 outbox advisory release failure observable','includes/class-wca-outbox.php','outbox_lock_release_failed_total');
t16h('R7 doctor-wide slot lock prevents cross-midnight lock split','includes/class-wca-repository.php',"wca-slot-doctor-");
t16h('R7 slot lock release failure observable','includes/class-wca-repository.php','slot_lock_release_failed_total');
t16h('R7 Future24 lock SQL failure explicit','includes/class-wca-future24.php','wca_future24_lock_read_failed');
t16h('R7 Future24 lock release failure observable','includes/class-wca-future24.php','future24_lock_release_failed_total');
t16h('R7 practitioner lock release failure observable','includes/class-wca-plan-guard.php','practitioner_ref_lock_release_failed_total');
t16h('R7 repository rollback uncertainty explicit','includes/class-wca-repository.php','wca_transaction_rollback_failed');
t16h('R7 appointment rollback uncertainty explicit','includes/class-swc-helpers.php','swc_transaction_rollback_failed');
t16h('R8 slot hold TTL rejects out-of-range intent','includes/class-wca-repository.php','wca_slot_ttl_range');
t16h('R8 slot hold TTL persists validated value','includes/class-wca-repository.php','time() + $ttl');
t16h('R8 clinical context TTL rejects out-of-range intent','includes/class-wca-repository.php','wca_context_ttl_range');
t16h('R8 payment amount uses strict integer range','includes/class-wca-repository.php','WCA_Service::strict_int( $amount_raw, 0, PHP_INT_MAX )');
t16h('R9 canonical dbDelta definitions receive column-index verification','includes/class-wca-schema.php','verify_definition_sql( $sql )');
t16h('R9 schema verifier checks columns','includes/class-wca-schema.php','wca_schema_columns_missing');
t16h('R9 schema verifier checks indexes','includes/class-wca-schema.php','wca_schema_indexes_missing');
t16h('R9 continuity schema uses full verifier','includes/class-wca-continuity-secure.php','WCA_Schema::verify_definition_sql( $sql )');
t16h('R9 Future24 schema uses full verifier','includes/class-wca-future24.php','WCA_Schema::verify_definition_sql( $sql )');
t16h('R9 runtime migration failures are contained','worldwide-clinic.php','runtime_migration_failed');
t16h('R9 runtime failure state is durable','worldwide-clinic.php','wca_runtime_migration_failure');
t16h('R9 legacy migration rollback uncertainty explicit','includes/class-swc-activator.php','rollback could not be verified; storage state is uncertain');
t16h('R9 uninstall removes primitive edit capability','uninstall.php','edit_swc_appointment');
t16h('R9 uninstall removes private delete capability','uninstall.php','delete_private_swc_appointments');
t16h('R10 protected appointment clinic read failure propagates','includes/class-wca-rest.php','if ( is_wp_error( $clinic_read_error ) ) { return $clinic_read_error; }');
t16h('R10 protected appointment service read failure propagates','includes/class-wca-rest.php','if ( is_wp_error( $service_read_error ) ) { return $service_read_error; }');
t16h('R10 opaque appointment lookup DB failure is explicit','includes/class-wca-opaque-api.php','wca_appointment_ref_read_failed');
t16h('R10 opaque clinic ref mutation consumes repository read errors','includes/class-wca-opaque-api.php','if ( is_wp_error( $read_error ) ) { return $read_error; }');
t16h('R10 public per-rule slot projection propagates DB read errors','includes/class-wca-service.php','if ( is_wp_error( $projection_read_error ) ) { return $projection_read_error; }');
t16h('R11 canonical subject helper failure never falls back to stale meta','includes/class-wca-authorization.php','wca_identity_claim_filter_invalid');
t16h('R11 identity filter cannot elevate approved claim','includes/class-wca-authorization.php','authoritative_claims');
t16h('R11 suspension filter is monotonic restrictive','includes/class-wca-authorization.php','filtered_claims');
t16h('R11 doctor serving filter cannot create native relationship','includes/class-wca-authorization.php','return $allowed && $filtered;');
t16h('R11 delegation scope filter cannot create a native scope','includes/class-wca-authorization.php','return $direct && $filtered;');
t16h('R11 canonical File00 age claim cannot be overwritten by local filter','includes/class-wca-central-governance.php','if ( ! $versioned_attempted ) {');
t16h('R11 legacy minor helper invalid response fails closed','includes/class-wca-central-governance.php','wca_age_claim_invalid_provider_response');
t16h('R11 File26 projection propagates upstream repository errors','includes/class-wca-central-governance.php','if ( is_wp_error( $projection ) ) { return $projection; }');
t16h('R12 malformed expected status is rejected before normalization','includes/class-wca-service.php','wca_transition_expected_status_invalid');
t16h('R12 persisted appointment state has strict validator','includes/class-swc-helpers.php','public static function status_strict');
t16h('R12 corrupt persisted appointment state fails closed','includes/class-swc-helpers.php','swc_appointment_state_corrupt');
t16h('R12 strict expected-state check rejects malformed status','includes/class-swc-helpers.php','swc_invalid_expected_status');
t16h('R12 slot-hold read DB failure is explicit','includes/class-wca-repository.php','wca_slot_hold_read_failed');
t16h('R12 slot booking DB write failure is explicit','includes/class-wca-repository.php','wca_hold_book_failed');
t16h('R12 appointment request propagates slot-hold read errors','includes/class-wca-service.php','if ( is_wp_error( $hold ) ) { return $hold; }');
t16h('R13 canonical slot wall-time conversion rejects DST ambiguity','includes/class-wca-service.php','SWC_Helpers::to_utc( (string) $date, (string) $time, $zone->getName() )');
t16h('R13 projected slot conflict expands buffer before','includes/class-wca-service.php','$conflict_start = $start_utc->modify');
t16h('R13 projected slot conflict expands buffer after','includes/class-wca-service.php','$conflict_end   = $end_utc->modify');
t16h('R13 canonical hold carries authoritative rule buffers','includes/class-wca-plan-guard.php',"'buffer_after'    => min( 240");
t16h('R13 atomic hold validates buffer range','includes/class-wca-repository.php','wca_slot_buffer_range');
t16h('R13 atomic hold rechecks stored buffered conflict window','includes/class-wca-repository.php','DATE_SUB(start_utc, INTERVAL buffer_before MINUTE)');
t16h('R14 appointment captures fee currency snapshot','includes/class-wca-service.php',"'fee_currency_snapshot'");
t16h('R14 appointment captures fee amount snapshot','includes/class-wca-service.php',"'fee_amount_minor_snapshot'");
t16h('R14 appointment captures policy snapshots','includes/class-wca-service.php',"'cancellation_policy_snapshot'");
t16h('R14 payment uses appointment-owned fee snapshot','includes/class-wca-service.php','appointment_fee_snapshot( $appointment_id )');
t16h('R14 payment provider must be approved by CF03 boundary','includes/class-wca-service.php','wca_cf03_approved_payment_providers');
t16h('R14 outbound payment intent carries provider','includes/class-wca-service.php',"'provider' => " . '$' . "provider");
t16h('R14 cancellation/no-show emits fee policy review','includes/class-wca-service.php','CF03.AppointmentFeePolicyReviewRequested.v1');
t16h('R14 unverified payment status is ignored','includes/class-wca-service.php','unverified_payment_status_ignored');
t16h('R14 verified CF03 status event is idempotent','includes/class-wca-service.php',"'payment_status_event'");
t16h('R14 payment status projection is durable','includes/class-wca-repository.php','public static function project_payment_status');
t16h('R14 unknown payment projection status rejected','includes/class-wca-repository.php','wca_payment_status_untrusted');
t16h('R14 authorized appointment includes safe payment projection','includes/class-wca-rest.php',"'payment'           => " . '$' . "payment_projection");
t16h('R15 calendar subject lookup storage failure explicit','includes/class-wca-calendar-link.php','wca_calendar_subject_read_failed');
t16h('R15 calendar appointment lookup storage failure explicit','includes/class-wca-calendar-link.php','wca_calendar_appointment_read_failed');
t16h('R15 signed provider webhook endpoint exists','includes/class-wca-calendar-link.php','calendar-provider-webhooks');
t16h('R15 provider signature verification delegated to adapter','includes/class-wca-calendar-link.php','wca_calendar_provider_verify_webhook');
t16h('R15 provider webhook event is idempotent','includes/class-wca-calendar-link.php',"'calendar_provider_webhook'");
t16h('R15 webhook never stores provider token','includes/class-wca-future24.php',"'provider_token_stored' => false");
t16h('R15 calendar provider mapping projection is durable','includes/class-wca-repository.php','upsert_calendar_mapping_from_provider');
t16h('R15 provider mapping cannot mutate canonical appointment','includes/class-wca-repository.php',"'canonical_appointment_mutated' => false");
t16h('R15 strict external busy DB failure explicit','includes/class-wca-future24.php','wca_external_busy_read_failed');
t16h('R15 standard slot response filters external busy','includes/class-wca-future24.php',"'external_calendar_filter_applied'");
t16h('R15 slot hold rejects external busy','includes/class-wca-future24.php','wca_external_calendar_busy');
t16h('R15 core hold cannot bypass external calendar','includes/class-wca-service.php','WCA_Future24::external_busy_conflict');
t16h('R16 complaint lifecycle has explicit transition law','includes/class-wca-contracts.php','complaint_transition_matrix');
t16h('R16 complaint purpose limit is server-owned','includes/class-wca-repository.php',"'purpose_limit'      => 'case_resolution_only'");
t16h('R16 evidence references are opaque and bounded','includes/class-wca-repository.php','wca_complaint_evidence_limit');
t16h('R16 complaint storage read failure explicit','includes/class-wca-repository.php','wca_complaint_read_failed');
t16h('R16 complaint state update uses CAS','includes/class-wca-repository.php','wca_complaint_version_conflict');
t16h('R16 complaint detail is protected opaque route','includes/class-wca-rest.php','complaints/(?P<ref>[0-9a-fA-F-]{36})');
t16h('R16 complainant appeal route exists','includes/class-wca-rest.php','/appeal');
t16h('R16 appeal is atomic with CF02 handoff','includes/class-wca-service.php','wca_complaint_appeal_transaction');
t16h('R16 CF02 status projection requires verified source','includes/class-wca-service.php','wca_cf02_case_unverified');
t16h('R16 CF02 status projection is idempotent','includes/class-wca-service.php',"'cf02_complaint_status'");
t16h('R16 complaint projection exposes fixed purpose limit','includes/class-wca-service.php',"'purpose_limit'=>'case_resolution_only'");
t16h('R17 canonical minor assertion uses strict boolean normalization','includes/class-wca-central-governance.php','true === $minor_raw || 1 === $minor_raw');
t16h('R17 guardian verification provider failure is degraded','includes/class-wca-central-governance.php','wca_guardian_verification_provider_failure');
t16h('R17 guardian relationship provider failure is degraded','includes/class-wca-central-governance.php','wca_guardian_relationship_provider_failure');
t16h('R17 active consent DB failure is explicit','includes/class-wca-continuity-secure.php','wca_active_consent_read_failed');
t16h('R17 intake propagates consent read failure','includes/class-wca-continuity-secure.php','$active_consent = self::active_consent');
t16h('R17 File17 context pre-reads consent strictly','includes/class-wca-continuity-secure.php','$messaging_consent = self::active_consent');
t16h('R17 follow-up propagates consent read failure','includes/class-wca-continuity-secure.php','$followup_consent = self::active_consent');
t16n('R18 continuity no longer has an independent activation hook','worldwide-clinic.php',"register_activation_hook( WCA_FILE, array( 'WCA_Continuity', 'activate' ) )");
t16n('R18 Future24 no longer has an independent activation hook','worldwide-clinic.php',"register_activation_hook( WCA_FILE, array( 'WCA_Future24', 'activate' ) )");
t16h('R18 rollback-aware activation installs continuity schema','includes/class-swc-activator.php','WCA_Continuity::install_schema();');
t16h('R18 rollback-aware activation installs Future24 schema','includes/class-swc-activator.php','WCA_Future24::install_schema();');
t16h('R18 runtime migration failure-state write is checked','worldwide-clinic.php','runtime_migration_failure_state_persistence_failed');
t16h('R18 stale migration-failure marker prevents boot','worldwide-clinic.php','runtime_migration_failure_state_clear_failed');
t16order('R18 migration-state evidence precedes schema-version commit marker','includes/class-wca-schema.php',"self::OPTION_MIGRATION_STATE, \$migration_state","self::OPTION_DB_VERSION, WCA_Contracts::SCHEMA_VERSION");
t16h('R18 incomplete activation rollback is never called successful','includes/class-swc-activator.php','activation failed and rollback is incomplete');
t16h('R18 deactivation clears daily health cron','includes/class-swc-activator.php',"wp_clear_scheduled_hook( 'wca_daily_health_snapshot' )");
t16h('R18 continuity health exposes boolean schema-current','includes/class-wca-continuity-secure.php',"'schema_current' => self::SCHEMA_VERSION");
t16h('R18 Future24 has explicit schema health','includes/class-wca-future24.php','public static function health()');
t16h('R18 overall health includes runtime migration failure state','includes/class-wca-observability.php',"'runtime_failure_absent'");
t16h('R18 CLI migration rejects WP Error','includes/class-wca-cli.php','if ( is_wp_error( $count ) )');
t16h('R18 destructive purge requires verified backup assertion','includes/class-wca-privacy.php','wca_purge_backup_verified');
t16h('R18 destructive purge blocks legal holds','includes/class-wca-privacy.php','wca_purge_legal_hold');
t16order('R18 purge preflight happens before first deletion batch','includes/class-swc-activator.php','WCA_Privacy::assert_purge_allowed','swc_purge_post_query');
t16h('R18 purge removes canonical File08 schema','includes/class-swc-activator.php','WCA_Schema::purge_canonical_data()');
t16h('R18 continuity exposes complete owned-data purge','includes/class-wca-continuity-secure.php','public static function purge_owned_data()');
t16h('R18 Future24 exposes complete owned-data purge','includes/class-wca-future24.php','public static function purge_owned_data()');
t16h('R18 partial destructive purge is observable','includes/class-swc-activator.php','irreversible_purge_partial_failure');
t16h('R19 canonical assets are shortcode/route scoped','includes/class-wca-plugin.php','has_shortcode( (string) $post->post_content, $shortcode )');
t16n('R19 canonical assets no longer load on every singular page','includes/class-wca-plugin.php','! WCA_Routes::route() && ! is_singular()');
t16h('R19 canonical client loads WordPress i18n runtime','includes/class-wca-plugin.php',"array( 'wp-i18n' )");
t16h('R19 continuity client loads WordPress i18n runtime','includes/class-wca-continuity-secure.php',"'wca-continuity', WCA_URL . 'assets/js/continuity.js', array( 'wp-i18n' )");
t16h('R19 Future24 client loads WordPress i18n runtime','includes/class-wca-future24.php',"'wca-future24', WCA_URL . 'assets/js/future24.js', array( 'wp-i18n' )");
t16h('R19 booking client has translation bridge','assets/js/clinic.js','function tr(message)');
t16h('R19 continuity client has translation bridge','assets/js/continuity.js','function tr(message)');
t16h('R19 Future24 client has translation bridge','assets/js/future24.js','function tr(message)');
t16h('R19 booking search has stale-response generation fence','assets/js/clinic.js','generation !== searchGeneration');
t16h('R19 slot hold has stale-response generation fence','assets/js/clinic.js','requestGeneration !== holdGeneration');
t16h('R19 failed alternate hold clears stale selected hold','assets/js/clinic.js','selectedHold = null; appointmentRequestKey = null; setStatus');
t16h('R19 booking detail change invalidates selected hold','assets/js/clinic.js',"field.addEventListener('change', invalidateSelection)");
t16h('R19 concurrent slot buttons are disabled during hold','assets/js/clinic.js',"item.setAttribute('aria-pressed', 'false'); item.disabled = true;");
if($fail){fwrite(STDERR,"T16 regression gate failed:\n- ".implode("\n- ",$fail)."\n");exit(1);} echo "T16 regression assertions passed: {$pass}/{$pass}\n";
