<?php
$root=dirname(__DIR__); $pass=0; $fail=array();
function t16h($label,$path,$needle){global $root,$pass,$fail;$s=file_get_contents($root.'/'.$path);if(is_string($s)&&false!==strpos($s,$needle)){echo 'PASS '.(++$pass).': '.$label."\n";}else{$fail[]=$label.' missing: '.$needle;}}
t16h('R1 continuity batch read fails closed','includes/class-wca-continuity-secure.php','null === $rows_raw && \'\' !== (string) $wpdb->last_error');
t16h('R1 continuity zero-delete readback fails closed','includes/class-wca-continuity-secure.php','null === $still_exists && \'\' !== (string) $wpdb->last_error');
t16h('R1 continuity completion read fails closed','includes/class-wca-continuity-secure.php','null === $more && \'\' !== (string) $wpdb->last_error');
t16h('R1 continuity guardian readback fails closed','includes/class-wca-continuity-secure.php','null === $guardian_remaining && \'\' !== (string) $wpdb->last_error');
t16h('R1 Future24 table probe fails closed','includes/class-wca-privacy.php','wca_privacy_future24_table_read_failed');
t16h('R1 privacy export propagates Future24 table failure','includes/class-wca-privacy.php','if ( is_wp_error( $table ) ) { return $table; }');
t16h('R1 strict audit history read exists','includes/class-swc-helpers.php','public static function audit_rows_strict');
t16h('R1 privacy export uses strict audit read','includes/class-swc-privacy.php','SWC_Helpers::audit_rows_strict');
t16h('R1 review eligibility duplicate read fails closed','includes/class-wca-repository.php','wca_review_eligibility_read_failed');
t16h('R4 continuity routes join HTTP idempotency guard','includes/class-wca-ten-review-hardening.php','continuity/appointments/[0-9a-fA-F-]{36}');
t16h('R4 continuity completion joins HTTP idempotency guard','includes/class-wca-ten-review-hardening.php','continuity/followups/[0-9a-fA-F-]{36}/complete');
t16h('R4 Future24 retains its own mutation guard','includes/class-wca-ten-review-hardening.php','strpos( $route, \'/wca/v1/future24/\' )');
t16h('R4 intake version guard runs after replay guard','includes/class-wca-continuity-guards.php',"enforce_intake_version' ), 20, 3");
t16h('R4 browser continuity sends idempotency header','assets/js/continuity.js',"'Idempotency-Key'");
t16h('R4 browser continuity persists ambiguous mutation key','assets/js/continuity.js','sessionStorage.setItem');
t16h('R4 browser mutation key uses secure randomness','assets/js/continuity.js','window.crypto.randomUUID');
t16h('R6 outbox claim write failure explicit','includes/class-wca-repository.php','wca_outbox_claim_write_failed');
t16h('R6 outbox successful claim requires readback','includes/class-wca-repository.php','wca_outbox_claim_readback_missing');
t16h('R6 ambiguous WP error retains reconciliation evidence','includes/class-wca-ten-review-hardening.php','http_idempotency_ambiguous_error_total');
t16h('R6 ambiguous response advertises reconciliation','includes/class-wca-ten-review-hardening.php','X-WCA-Reconciliation-Required');
t16h('R6 unverifiable response fails closed','includes/class-wca-ten-review-hardening.php','wca_idempotency_response_unverifiable');
t16h('R6 idempotency release DB failure observable','includes/class-wca-repository.php','idempotency_release_db_failed_total');
t16h('R6 outbox advisory release failure observable','includes/class-wca-outbox.php','outbox_lock_release_failed_total');
t16h('R7 doctor-wide slot lock prevents cross-midnight lock split','includes/class-wca-repository.php',"wca-slot-doctor-");
t16h('R7 slot lock release failure observable','includes/class-wca-repository.php','slot_lock_release_failed_total');
t16h('R7 Future24 lock SQL failure explicit','includes/class-wca-future24.php','wca_future24_lock_read_failed');
t16h('R7 Future24 lock release failure observable','includes/class-wca-future24.php','future24_lock_release_failed_total');
t16h('R7 practitioner lock release failure observable','includes/class-wca-plan-guard.php','practitioner_ref_lock_release_failed_total');
t16h('R7 repository rollback uncertainty explicit','includes/class-wca-repository.php','wca_transaction_rollback_failed');
t16h('R7 appointment rollback uncertainty explicit','includes/class-swc-helpers.php','swc_transaction_rollback_failed');
t16h('R8 slot hold TTL rejects out-of-range intent','includes/class-wca-repository.php','wca_slot_ttl_range');
t16h('R8 slot hold TTL persists validated value','includes/class-wca-repository.php','time() + $ttl');
t16h('R8 clinical context TTL rejects out-of-range intent','includes/class-wca-repository.php','wca_context_ttl_range');
t16h('R8 payment amount uses strict integer range','includes/class-wca-repository.php','WCA_Service::strict_int( $amount_raw, 0, PHP_INT_MAX )');
t16h('R9 canonical dbDelta definitions receive column-index verification','includes/class-wca-schema.php','verify_definition_sql( $sql )');
t16h('R9 schema verifier checks columns','includes/class-wca-schema.php','wca_schema_columns_missing');
t16h('R9 schema verifier checks indexes','includes/class-wca-schema.php','wca_schema_indexes_missing');
t16h('R9 continuity schema uses full verifier','includes/class-wca-continuity-secure.php','WCA_Schema::verify_definition_sql( $sql )');
t16h('R9 Future24 schema uses full verifier','includes/class-wca-future24.php','WCA_Schema::verify_definition_sql( $sql )');
t16h('R9 runtime migration failures are contained','worldwide-clinic.php','runtime_migration_failed');
t16h('R9 runtime failure state is durable','worldwide-clinic.php','wca_runtime_migration_failure');
t16h('R9 legacy migration rollback uncertainty explicit','includes/class-swc-activator.php','rollback could not be verified; storage state is uncertain');
t16h('R9 uninstall removes primitive edit capability','uninstall.php','edit_swc_appointment');
t16h('R9 uninstall removes private delete capability','uninstall.php','delete_private_swc_appointments');
t16h('R10 protected appointment clinic read failure propagates','includes/class-wca-rest.php','if ( is_wp_error( $clinic_read_error ) ) { return $clinic_read_error; }');
t16h('R10 protected appointment service read failure propagates','includes/class-wca-rest.php','if ( is_wp_error( $service_read_error ) ) { return $service_read_error; }');
t16h('R10 opaque appointment lookup DB failure is explicit','includes/class-wca-opaque-api.php','wca_appointment_ref_read_failed');
t16h('R10 opaque clinic ref mutation consumes repository read errors','includes/class-wca-opaque-api.php','if ( is_wp_error( $read_error ) ) { return $read_error; }');
t16h('R10 public per-rule slot projection propagates DB read errors','includes/class-wca-service.php','if ( is_wp_error( $projection_read_error ) ) { return $projection_read_error; }');
if($fail){fwrite(STDERR,"T16 regression gate failed:\n- ".implode("\n- ",$fail)."\n");exit(1);} echo "T16 regression assertions passed: {$pass}/{$pass}\n";
