<?php
/** File 08 tenth fresh ten-round corrective regression gate. */
$root=dirname(__DIR__); $failures=array(); $checks=0;
function t10src($p){global $root,$failures;$f=$root.'/'.$p;if(!is_file($f)){$failures[]='Missing '.$p;return '';} $s=file_get_contents($f);return is_string($s)?$s:'';}
function t10has($l,$s,$n){global $failures,$checks;$checks++;if(false===strpos($s,$n)){$failures[]=$l.' missing: '.$n;}}
function t10lacks($l,$s,$n){global $failures,$checks;$checks++;if(false!==strpos($s,$n)){$failures[]=$l.' forbidden: '.$n;}}
$boot=t10src('worldwide-clinic.php'); $contracts=t10src('includes/class-wca-contracts.php'); $repo=t10src('includes/class-wca-repository.php'); $service=t10src('includes/class-wca-service.php'); $rest=t10src('includes/class-wca-rest.php'); $hard=t10src('includes/class-wca-ten-review-hardening.php');
foreach(array('wca_appointment_request_transaction','wca_clinic_create_transaction','wca_clinic_review_transaction','wca_clinic_activate_transaction','wca_branch_create_transaction','wca_service_mutation_transaction','wca_availability_mutation_transaction','wca_complaint_transaction','wca_payment_intent_transaction') as $t){t10has('owner transaction',$service,$t);}
foreach(array('AppointmentRequested.v1','ClinicActivated.v1','ClinicBranchChanged.v1','ClinicAvailabilityChanged.v1','AppointmentComplaintSubmitted.v1','CF03.PaymentIntentRequested.v1') as $t){t10has('required evidence',$service,$t);}
t10has('generic transaction helper',$repo,'public static function transaction'); t10has('rollback',$repo,"query( 'ROLLBACK' )");
t10has('idempotency status repository',$repo,'public static function idempotency_status'); t10has('mutation status route',$hard,"'/mutation-status'"); t10has('replay finalization fail closed',$hard,'wca_idempotency_finalize_failed'); t10has('reconciliation flag',$hard,"'reconciliation_required' => true");
t10has('branch timezone validation',$service,'wca_branch_timezone'); t10has('availability timezone validation',$service,'wca_availability_timezone'); t10has('availability window validation',$service,'wca_availability_window'); t10has('availability range validation',$service,'wca_availability_effective_range');
t10has('clinic cursor',$rest,"get_param( 'cursor' )"); t10has('opaque cursor state',$rest,"'wca_clinic_cursor_' . md5("); t10has('next cursor',$rest,"'next_cursor'"); t10has('conditional request',$rest,"get_header( 'If-None-Match' )"); t10has('etag header',$rest,"header( 'ETag'"); t10has('cursor keyset repository',$repo,'c.updated_at<%s OR (c.updated_at=%s AND c.id<%d)');
t10has('plugin 1.2.12',$boot,'Version: 1.2.12'); t10has('runtime 1.2.12',$contracts,"RUNTIME_VERSION                 = '1.2.12'"); t10has('schema stays 3.2.0',$contracts,"SCHEMA_VERSION                  = '3.2.0'");
$runtime=implode("\n",array($boot,$contracts,$repo,$service,$rest,$hard)); foreach(array('eval(','base64_decode(','shell_exec(','unserialize(') as $t){t10lacks('forbidden runtime primitive',$runtime,$t);} if($failures){fwrite(STDERR,"File 08 tenth-ten-review regression gate failed:\n- ".implode("\n- ",$failures)."\n");exit(1);} echo 'File 08 tenth fresh ten-round regression assertions passed: '.$checks.'/'.$checks.".\n";
