<?php
defined( 'ABSPATH' ) || exit;
final class SWC_Helpers {
	const TYPE = 'swc_appointment';
	public static function statuses() { return array( 'requested' => 'Requested', 'under-review' => 'Under Review', 'accepted' => 'Accepted', 'reschedule-requested' => 'Reschedule Requested', 'declined' => 'Declined', 'cancelled' => 'Cancelled', 'completed' => 'Completed' ); }
	public static function status( $id ) { $s = get_post_meta( absint( $id ), '_swc_status', true ); return isset( self::statuses()[ $s ] ) ? $s : 'requested'; }
	public static function meta( $id, $key, $default = '' ) { $v = get_post_meta( absint( $id ), '_swc_' . $key, true ); return '' === $v ? $default : $v; }
	public static function doctor_meta( $id, $key, $default = '' ) { $v = get_user_meta( absint( $id ), '_swc_' . $key, true ); return '' === $v ? $default : $v; }
	public static function doctor_ids() { $users = get_users( array( 'role' => 'sabri_doctor_verified', 'number' => 250, 'fields' => 'ID' ) ); $ids = array_values( array_filter( array_map( 'absint', $users ), function( $id ) { return SDD_Helpers::is_public( $id ) || SDD_Helpers::is_founder( $id ); } ) ); $founder = SDD_Helpers::founder_id(); if ( $founder && get_userdata( $founder ) ) { array_unshift( $ids, $founder ); } return array_values( array_unique( $ids ) ); }
	public static function can_doctor_manage( $appointment_id, $user_id = 0 ) { $user_id = $user_id ? absint( $user_id ) : get_current_user_id(); return $user_id && absint( self::meta( $appointment_id, 'doctor_id' ) ) === $user_id && SDD_Helpers::is_verified( $user_id ); }
	public static function can_patient_manage( $appointment_id, $user_id = 0 ) { $user_id = $user_id ? absint( $user_id ) : get_current_user_id(); return $user_id && absint( get_post_field( 'post_author', $appointment_id ) ) === $user_id; }
	public static function can_view( $id ) { return self::can_patient_manage( $id ) || self::can_doctor_manage( $id ) || current_user_can( 'manage_worldwide_clinic' ); }
	public static function timezones() { return timezone_identifiers_list(); }
	public static function to_utc( $date, $time, $timezone ) { try { $zone = new DateTimeZone( $timezone ); $dt = DateTime::createFromFormat( '!Y-m-d H:i', $date . ' ' . $time, $zone ); if ( ! $dt ) { return ''; } $dt->setTimezone( new DateTimeZone( 'UTC' ) ); return $dt->format( 'Y-m-d H:i:s' ); } catch ( Exception $e ) { return ''; } }
	public static function display_time( $utc, $timezone ) { if ( ! $utc ) { return 'Not scheduled'; } try { $dt = new DateTime( $utc, new DateTimeZone( 'UTC' ) ); $dt->setTimezone( new DateTimeZone( $timezone ) ); return $dt->format( 'M j, Y · g:i A' ) . ' (' . $timezone . ')'; } catch ( Exception $e ) { return 'Time unavailable'; } }
	public static function phone( $value ) { return SPD_Helpers::clean_phone( $value ); }
	public static function whatsapp( $value ) { return SPD_Helpers::whatsapp_url( $value ); }
	public static function pages() { return (array) get_option( 'swc_page_map', array() ); }
	public static function audit( $appointment, $action, $note = '' ) { global $wpdb; $wpdb->insert( $wpdb->prefix . 'swc_audit_log', array( 'appointment_id' => absint( $appointment ), 'actor_id' => get_current_user_id(), 'action' => sanitize_key( $action ), 'note' => sanitize_textarea_field( $note ), 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s', '%s', '%s' ) ); }
	public static function navigation() { $specs = array( 'home'=>array('Home','sabri-platform-home'),'news'=>array('News','sabri-news'),'founder'=>array('Founder','sabri-founder'),'learn'=>array('Learn Sabri Classical Homeopathy','learn-sabri-classical-homeopathy'),'encyclopedia'=>array('Encyclopedia','homeopathy-encyclopedia'),'doctors'=>array('Doctors','homeopathy-doctors'),'clinic'=>array('Worldwide Clinic','worldwide-clinic'),'videos'=>array('Video Wall','video-wall'),'reels'=>array('Reels','reels'),'pdf'=>array('PDF Library','pdf-library'),'radar'=>array('Radar','homeopathy-radar'),'ai'=>array('Sabri Classical Homeopathy AI','sabri-classical-homeopathy-ai'),'network'=>array('Network','homeopathy-network'),'marketplace'=>array('Marketplace','homeopathy-marketplace') ); $pages=(array)get_option('spf_page_map',array()); $out='<nav class="swc-main-nav" aria-label="Main platform navigation">'; foreach($specs as $key=>$spec){$url=!empty($pages[$key])?get_permalink($pages[$key]):home_url('/'.$spec[1].'/');$out.='<a class="'.('clinic'===$key?'is-active':'').'" href="'.esc_url($url).'">'.esc_html($spec[0]).'</a>';} return $out.'</nav>'; }
}
