<?php
defined( 'ABSPATH' ) || exit;
final class SWC_Privacy {
	public function hooks(){add_filter('wp_privacy_personal_data_exporters',array($this,'exporters'));add_filter('wp_privacy_personal_data_erasers',array($this,'erasers'));add_action('admin_init',array($this,'policy'));}
	public function exporters($e){$e['worldwide-clinic']=array('exporter_friendly_name'=>'Worldwide Clinic Appointments','callback'=>array($this,'export'));return $e;}
	public function export($email,$page=1){$u=get_user_by('email',$email);if(!$u){return array('data'=>array(),'done'=>true);}$items=get_posts(array('post_type'=>SWC_Helpers::TYPE,'post_status'=>'publish','author'=>$u->ID,'posts_per_page'=>100,'paged'=>max(1,absint($page))));$data=array();foreach($items as $a){$fields=array('Status'=>SWC_Helpers::statuses()[SWC_Helpers::status($a->ID)],'Doctor'=>get_the_author_meta('display_name',SWC_Helpers::meta($a->ID,'doctor_id')),'Consultation type'=>SWC_Helpers::meta($a->ID,'consultation_type'),'Requested time UTC'=>SWC_Helpers::meta($a->ID,'preferred_at_utc'),'Patient time zone'=>SWC_Helpers::meta($a->ID,'patient_timezone'),'Country'=>SWC_Helpers::meta($a->ID,'country'),'City'=>SWC_Helpers::meta($a->ID,'city'),'Phone'=>SWC_Helpers::meta($a->ID,'phone'),'WhatsApp'=>SWC_Helpers::meta($a->ID,'whatsapp'),'Reason'=>SWC_Helpers::meta($a->ID,'reason'),'Duration'=>SWC_Helpers::meta($a->ID,'duration'));$rows=array();foreach($fields as $name=>$value){$rows[]=array('name'=>$name,'value'=>$value);}$data[]=array('group_id'=>'worldwide-clinic','group_label'=>'Worldwide Clinic Appointments','item_id'=>'appointment-'.$a->ID,'data'=>$rows);}return array('data'=>$data,'done'=>count($items)<100);}
	public function erasers($e){$e['worldwide-clinic']=array('eraser_friendly_name'=>'Worldwide Clinic Appointments','callback'=>array($this,'erase'));return $e;}
	public function erase($email,$page=1){$u=get_user_by('email',$email);if(!$u){return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);}$items=get_posts(array('post_type'=>SWC_Helpers::TYPE,'post_status'=>'publish','author'=>$u->ID,'posts_per_page'=>100,'paged'=>max(1,absint($page))));foreach($items as $a){foreach(array('country','city','phone','whatsapp','reason','duration','doctor_note') as $key){update_post_meta($a->ID,'_swc_'.$key,'[Removed through privacy request]');}update_post_meta($a->ID,'_swc_status','cancelled');update_post_meta($a->ID,'_swc_erased','1');SWC_Helpers::audit($a->ID,'privacy-erasure','Personal fields removed');}return array('items_removed'=>(bool)$items,'items_retained'=>(bool)$items,'messages'=>array('Minimal scheduling and audit records may be retained for security and legal accountability.'),'done'=>count($items)<100);}
	public function policy(){if(function_exists('wp_add_privacy_policy_content')){wp_add_privacy_policy_content('Worldwide Clinic','<p class="privacy-policy-tutorial">The clinic module processes appointment time, time zone, selected doctor, consultation method, location, phone, WhatsApp number, a brief reason, consent time, status, and audit history to provide private appointment scheduling. Access is limited to the patient, selected verified doctor, and authorized administrators.</p>');}}
}

