<?php
defined( 'ABSPATH' ) || exit;
final class SWC_Activator {
	public static function activate() { if ( ! class_exists( 'SPD_Helpers' ) || ! class_exists( 'SDD_Helpers' ) ) { deactivate_plugins( plugin_basename( SWC_FILE ) ); wp_die( esc_html__( 'Activate Files 03 and 07 before activating Worldwide Clinic.', 'worldwide-clinic' ), '', array( 'back_link' => true ) ); } self::role(); self::founder(); self::register_type(); self::tables(); self::pages(); update_option( 'swc_version', SWC_VERSION, false ); set_transient( 'swc_activation_notice', '1', 120 ); flush_rewrite_rules(); }
	public static function deactivate() { $m=(array)get_option('swc_page_map',array()); if(!empty($m['clinic'])){self::restore($m['clinic'],'[swc_worldwide_clinic]','[sabri_platform_module key="clinic"]');} flush_rewrite_rules(); }
	private static function restore($id,$current,$fallback){$p=get_post(absint($id));if($p instanceof WP_Post&&trim($p->post_content)===$current){wp_update_post(array('ID'=>$p->ID,'post_content'=>$fallback));}}
	private static function role(){ $a=get_role('administrator'); if($a){$a->add_cap('manage_worldwide_clinic');} }
	private static function founder(){ $id=SDD_Helpers::founder_id(); if($id&&get_userdata($id)){ $user=new WP_User($id); $user->add_role('sabri_doctor_verified'); update_user_meta($id,'_spd_account_type','doctor'); update_user_meta($id,'_spd_verification_status','verified'); if(''===get_user_meta($id,'_swc_online',true)){update_user_meta($id,'_swc_online','1');update_user_meta($id,'_swc_in_person','1');update_user_meta($id,'_swc_accepting','1');} } }
	public static function register_type(){ register_post_type(SWC_Helpers::TYPE,array('labels'=>array('name'=>'Clinic Appointments','singular_name'=>'Clinic Appointment'),'public'=>false,'show_ui'=>false,'show_in_rest'=>false,'exclude_from_search'=>true,'supports'=>array('title','author'),'capability_type'=>'post','map_meta_cap'=>true)); }
	private static function tables(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE {$wpdb->prefix}swc_audit_log (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,appointment_id bigint(20) unsigned NOT NULL,actor_id bigint(20) unsigned NOT NULL,action varchar(40) NOT NULL,note text NOT NULL,created_at datetime NOT NULL,PRIMARY KEY  (id),KEY appointment_id (appointment_id)) {$c};");}
	private static function pages(){ $spf=(array)get_option('spf_page_map',array());$map=(array)get_option('swc_page_map',array());$map['clinic']=self::page(!empty($spf['clinic'])?absint($spf['clinic']):0,'Worldwide Clinic','worldwide-clinic','[swc_worldwide_clinic]');$map['request']=self::page(0,'Request an Appointment','request-appointment','[swc_request_appointment]');$map['patient']=self::page(0,'My Appointments','my-appointments','[swc_my_appointments]');$map['doctor']=self::page(0,'Doctor Appointments','doctor-appointments','[swc_doctor_appointments]');$map['availability']=self::page(0,'Doctor Availability','doctor-availability','[swc_doctor_availability]');update_option('swc_page_map',$map,false);$spf['clinic']=$map['clinic'];update_option('spf_page_map',$spf,false);}
	private static function page($id,$title,$slug,$code){$p=$id?get_post($id):get_page_by_path($slug);if($p instanceof WP_Post){$managed=get_post_meta($p->ID,'_spf_managed_page',true)||get_post_meta($p->ID,'_swc_managed_page',true);if($managed||false!==strpos($p->post_content,'[sabri_platform_module')||false!==strpos($p->post_content,'[swc_')){wp_update_post(array('ID'=>$p->ID,'post_content'=>$code));update_post_meta($p->ID,'_swc_managed_page','1');}return $p->ID;}$id=wp_insert_post(array('post_title'=>$title,'post_name'=>$slug,'post_content'=>$code,'post_status'=>'publish','post_type'=>'page'),true);if(!is_wp_error($id)){update_post_meta($id,'_swc_managed_page','1');return $id;}return 0;}
}
