#!/usr/bin/env python3
from pathlib import Path
import re, sys

ROOT = Path(__file__).resolve().parents[1]

def read(path):
    return (ROOT / path).read_text()

def write(path, text):
    (ROOT / path).write_text(text)

def replace_once(path, old, new):
    text = read(path)
    if old not in text:
        raise SystemExit(f"anchor missing in {path}: {old[:120]!r}")
    text2 = text.replace(old, new, 1)
    write(path, text2)

def regex_once(path, pattern, replacement):
    text = read(path)
    text2, count = re.subn(pattern, replacement, text, count=1, flags=re.S)
    if count != 1:
        raise SystemExit(f"regex anchor count {count} in {path}: {pattern[:120]!r}")
    write(path, text2)

def append_before(path, marker, block):
    text = read(path)
    if marker not in text:
        raise SystemExit(f"marker missing in {path}: {marker!r}")
    if block.strip() in text:
        return
    write(path, text.replace(marker, block + marker, 1))

round_no = int(sys.argv[1])

if round_no == 1:
    path = 'includes/class-wca-repository.php'
    old = """\tpublic static function transaction( $callback, $error_code = 'wca_transaction_failed' ) {\n\t\tglobal $wpdb;\n\t\t$wpdb->query( 'START TRANSACTION' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\ttry {\n\t\t\t$result = call_user_func( $callback );\n\t\t\tif ( is_wp_error( $result ) ) {\n\t\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\treturn $result;\n\t\t\t}\n\t\t\t$wpdb->query( 'COMMIT' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\treturn $result;\n\t\t} catch ( Throwable $error ) {\n\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\treturn new WP_Error( sanitize_key( $error_code ), __( 'The mutation could not be committed safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t}\n\t}\n"""
    new = """\tpublic static function transaction( $callback, $error_code = 'wca_transaction_failed' ) {\n\t\tglobal $wpdb;\n\t\t$started = $wpdb->query( 'START TRANSACTION' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\tif ( false === $started ) {\n\t\t\treturn new WP_Error( sanitize_key( $error_code . '_start' ), __( 'The mutation transaction could not be started safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t}\n\t\ttry {\n\t\t\t$result = call_user_func( $callback );\n\t\t\tif ( is_wp_error( $result ) ) {\n\t\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\treturn $result;\n\t\t\t}\n\t\t\t$committed = $wpdb->query( 'COMMIT' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\tif ( false === $committed ) {\n\t\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\treturn new WP_Error( sanitize_key( $error_code . '_commit' ), __( 'The mutation transaction could not be committed safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t\t}\n\t\t\treturn $result;\n\t\t} catch ( Throwable $error ) {\n\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\treturn new WP_Error( sanitize_key( $error_code ), __( 'The mutation could not be committed safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t}\n\t}\n"""
    replace_once(path, old, new)

elif round_no == 2:
    path = 'includes/class-swc-helpers.php'
    old = """\tprivate static function with_database_transaction( $appointment_id, $callback ) {\n\t\tglobal $wpdb;\n\t\t$wpdb->query( 'START TRANSACTION' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\ttry {\n\t\t\t$result = call_user_func( $callback );\n\t\t\tif ( is_wp_error( $result ) ) {\n\t\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\twp_cache_delete( absint( $appointment_id ), 'post_meta' );\n\t\t\t\treturn $result;\n\t\t\t}\n\t\t\t$wpdb->query( 'COMMIT' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\treturn $result;\n\t\t} catch ( Throwable $error ) {\n\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\twp_cache_delete( absint( $appointment_id ), 'post_meta' );\n\t\t\treturn new WP_Error( 'swc_transaction_failed', __( 'The appointment update could not be committed safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t}\n\t}\n"""
    new = """\tprivate static function with_database_transaction( $appointment_id, $callback ) {\n\t\tglobal $wpdb;\n\t\t$started = $wpdb->query( 'START TRANSACTION' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\tif ( false === $started ) {\n\t\t\treturn new WP_Error( 'swc_transaction_start_failed', __( 'The appointment transaction could not be started safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t}\n\t\ttry {\n\t\t\t$result = call_user_func( $callback );\n\t\t\tif ( is_wp_error( $result ) ) {\n\t\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\twp_cache_delete( absint( $appointment_id ), 'post_meta' );\n\t\t\t\treturn $result;\n\t\t\t}\n\t\t\t$committed = $wpdb->query( 'COMMIT' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\tif ( false === $committed ) {\n\t\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\twp_cache_delete( absint( $appointment_id ), 'post_meta' );\n\t\t\t\treturn new WP_Error( 'swc_transaction_commit_failed', __( 'The appointment transaction could not be committed safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t\t}\n\t\t\treturn $result;\n\t\t} catch ( Throwable $error ) {\n\t\t\t$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\twp_cache_delete( absint( $appointment_id ), 'post_meta' );\n\t\t\treturn new WP_Error( 'swc_transaction_failed', __( 'The appointment update could not be committed safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) );\n\t\t}\n\t}\n"""
    replace_once(path, old, new)

elif round_no == 3:
    path = 'includes/class-swc-helpers.php'
    old = """\tpublic static function with_resource_lock( $resource, $callback ) {\n\t\t$resource = substr( preg_replace( '/[^a-z0-9_-]/', '-', strtolower( (string) $resource ) ), 0, 120 );\n\t\t$key      = 'swc_lock_' . md5( $resource );\n\t\t$token    = wp_generate_uuid4();\n\t\t$now      = time();\n\t\t$value    = wp_json_encode( array( 'token' => $token, 'time' => $now, 'resource' => $resource ) );\n\t\tif ( ! add_option( $key, $value, '', false ) ) {\n\t\t\t$existing = json_decode( (string) get_option( $key, '' ), true );\n\t\t\tif ( is_array( $existing ) && ! empty( $existing['time'] ) && $now - absint( $existing['time'] ) > 30 ) {\n\t\t\t\tdelete_option( $key );\n\t\t\t\tadd_option( $key, $value, '', false );\n\t\t\t}\n\t\t}\n\t\tif ( (string) get_option( $key, '' ) !== $value ) {\n\t\t\treturn new WP_Error( 'swc_locked', __( 'This scheduling resource is being updated. Refresh and try again.', 'worldwide-clinic-appointments' ) );\n\t\t}\n\t\ttry {\n\t\t\treturn call_user_func( $callback );\n\t\t} finally {\n\t\t\tif ( (string) get_option( $key, '' ) === $value ) {\n\t\t\t\tdelete_option( $key );\n\t\t\t}\n\t\t}\n\t}\n"""
    new = """\tpublic static function with_resource_lock( $resource, $callback ) {\n\t\tglobal $wpdb;\n\t\t$resource = substr( preg_replace( '/[^a-z0-9_-]/', '-', strtolower( (string) $resource ) ), 0, 120 );\n\t\t$key      = 'swc_lock_' . md5( $resource );\n\t\t$token    = wp_generate_uuid4();\n\t\t$now      = time();\n\t\t$value    = wp_json_encode( array( 'token' => $token, 'time' => $now, 'resource' => $resource ) );\n\t\tif ( ! add_option( $key, $value, '', false ) ) {\n\t\t\t$existing_raw = (string) get_option( $key, '' );\n\t\t\t$existing = json_decode( $existing_raw, true );\n\t\t\tif ( is_array( $existing ) && ! empty( $existing['time'] ) && $now - absint( $existing['time'] ) > 300 ) {\n\t\t\t\t$swapped = $wpdb->query( $wpdb->prepare( \"UPDATE {$wpdb->options} SET option_value=%s WHERE option_name=%s AND option_value=%s\", $value, $key, $existing_raw ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery\n\t\t\t\twp_cache_delete( $key, 'options' );\n\t\t\t\tif ( 1 !== (int) $swapped ) {\n\t\t\t\t\treturn new WP_Error( 'swc_locked', __( 'This scheduling resource is being updated. Refresh and try again.', 'worldwide-clinic-appointments' ) );\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t\tif ( (string) get_option( $key, '' ) !== $value ) {\n\t\t\treturn new WP_Error( 'swc_locked', __( 'This scheduling resource is being updated. Refresh and try again.', 'worldwide-clinic-appointments' ) );\n\t\t}\n\t\ttry {\n\t\t\treturn call_user_func( $callback );\n\t\t} finally {\n\t\t\tif ( (string) get_option( $key, '' ) === $value ) {\n\t\t\t\tdelete_option( $key );\n\t\t\t}\n\t\t}\n\t}\n"""
    replace_once(path, old, new)

elif round_no == 4:
    path = 'includes/class-wca-repository.php'
    old = """\tpublic static function complete_outbox( $id ) {\n\t\tglobal $wpdb;\n\t\t$table = WCA_Schema::tables()['outbox'];\n\t\treturn false !== $wpdb->update( $table, array( 'status' => 'delivered', 'delivered_at' => self::now(), 'updated_at' => self::now(), 'locked_at' => null, 'locked_by' => '' ), array( 'id' => absint( $id ) ) );\n\t}\n\n\tpublic static function fail_outbox( $id, $error, $attempts ) {\n\t\tglobal $wpdb;\n\t\t$table   = WCA_Schema::tables()['outbox'];\n\t\t$attempts = absint( $attempts ) + 1;\n\t\t$status  = $attempts >= 8 ? 'dead_letter' : 'retry';\n\t\t$delay   = min( DAY_IN_SECONDS, (int) pow( 2, min( 10, $attempts ) ) * 60 );\n\t\treturn false !== $wpdb->update( $table, array( 'status' => $status, 'attempts' => $attempts, 'last_error' => substr( sanitize_text_field( $error ), 0, 500 ), 'next_attempt_at' => gmdate( 'Y-m-d H:i:s', time() + $delay ), 'updated_at' => self::now(), 'locked_at' => null, 'locked_by' => '' ), array( 'id' => absint( $id ) ) );\n\t}\n"""
    new = """\tpublic static function complete_outbox( $id, $worker = '' ) {\n\t\tglobal $wpdb;\n\t\t$table = WCA_Schema::tables()['outbox'];\n\t\t$worker = sanitize_text_field( $worker );\n\t\tif ( '' === $worker ) { return false; }\n\t\t$updated = $wpdb->update( $table, array( 'status' => 'delivered', 'delivered_at' => self::now(), 'updated_at' => self::now(), 'locked_at' => null, 'locked_by' => '' ), array( 'id' => absint( $id ), 'status' => 'processing', 'locked_by' => $worker ) );\n\t\treturn 1 === (int) $updated;\n\t}\n\n\tpublic static function fail_outbox( $id, $error, $attempts, $worker = '' ) {\n\t\tglobal $wpdb;\n\t\t$table   = WCA_Schema::tables()['outbox'];\n\t\t$worker = sanitize_text_field( $worker );\n\t\tif ( '' === $worker ) { return false; }\n\t\t$attempts = absint( $attempts ) + 1;\n\t\t$status  = $attempts >= 8 ? 'dead_letter' : 'retry';\n\t\t$delay   = min( DAY_IN_SECONDS, (int) pow( 2, min( 10, $attempts ) ) * 60 );\n\t\t$updated = $wpdb->update( $table, array( 'status' => $status, 'attempts' => $attempts, 'last_error' => substr( sanitize_text_field( $error ), 0, 500 ), 'next_attempt_at' => gmdate( 'Y-m-d H:i:s', time() + $delay ), 'updated_at' => self::now(), 'locked_at' => null, 'locked_by' => '' ), array( 'id' => absint( $id ), 'status' => 'processing', 'locked_by' => $worker ) );\n\t\treturn 1 === (int) $updated;\n\t}\n"""
    replace_once(path, old, new)

elif round_no == 5:
    path = 'includes/class-wca-outbox.php'
    old = """\t\t\t\t\tWCA_Repository::complete_outbox( absint( $item['id'] ) );\n\t\t\t\t\tWCA_Observability::metric( 'outbox_delivered_total', 1, array( 'topic' => self::metric_topic( $item['topic'] ) ) );\n\t\t\t\t} catch ( Throwable $error ) {\n\t\t\t\t\tWCA_Repository::fail_outbox( absint( $item['id'] ), $error->getMessage(), $attempts );\n\t\t\t\t\tWCA_Observability::log( 'error', 'outbox_delivery_failed', array(\n"""
    new = """\t\t\t\t\tif ( ! WCA_Repository::complete_outbox( absint( $item['id'] ), $worker ) ) {\n\t\t\t\t\t\tthrow new RuntimeException( 'Outbox delivery completed externally but durable worker-fenced finalization failed.' );\n\t\t\t\t\t}\n\t\t\t\t\tWCA_Observability::metric( 'outbox_delivered_total', 1, array( 'topic' => self::metric_topic( $item['topic'] ) ) );\n\t\t\t\t} catch ( Throwable $error ) {\n\t\t\t\t\t$failed = WCA_Repository::fail_outbox( absint( $item['id'] ), $error->getMessage(), $attempts, $worker );\n\t\t\t\t\tif ( ! $failed ) { WCA_Observability::metric( 'outbox_finalize_contention_total', 1 ); }\n\t\t\t\t\tWCA_Observability::log( 'error', 'outbox_delivery_failed', array(\n"""
    replace_once(path, old, new)

elif round_no == 6:
    path = 'includes/class-wca-outbox.php'
    old = """\t\t$sent    = false;\n\t\tforeach ( array_unique( array_filter( array_map( 'absint', (array) ( $payload['recipients'] ?? array() ) ) ) ) as $user_id ) {\n\t\t\t$user = get_userdata( $user_id );\n\t\t\tif ( $user && is_email( $user->user_email ) ) {\n\t\t\t\t$sent = wp_mail( $user->user_email, $subject, $message ) || $sent;\n\t\t\t}\n\t\t}\n\t\treturn $sent || empty( $payload['recipients'] ) ? true : new WP_Error( 'wca_mail_delivery', 'Notification fallback delivery failed.' );\n"""
    new = """\t\t$recipients = array_unique( array_filter( array_map( 'absint', (array) ( $payload['recipients'] ?? array() ) ) ) );\n\t\tif ( empty( $recipients ) ) { return true; }\n\t\t$all_sent = true;\n\t\tforeach ( $recipients as $user_id ) {\n\t\t\t$user = get_userdata( $user_id );\n\t\t\tif ( ! $user || ! is_email( $user->user_email ) || ! wp_mail( $user->user_email, $subject, $message ) ) {\n\t\t\t\t$all_sent = false;\n\t\t\t}\n\t\t}\n\t\treturn $all_sent ? true : new WP_Error( 'wca_mail_delivery', 'Notification fallback did not deliver to every intended recipient.' );\n"""
    replace_once(path, old, new)

elif round_no == 7:
    path = 'includes/class-wca-service.php'
    old = """\t\t$idempotency_key = sanitize_text_field( $data['idempotency_key'] ?? '' );\n\t\tif ( ! $idempotency_key ) { return new WP_Error( 'wca_idempotency_required', __( 'An idempotency key is required.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n"""
    new = """\t\t$idempotency_key = sanitize_text_field( $data['idempotency_key'] ?? '' );\n\t\tif ( ! preg_match( '/^[A-Za-z0-9._:-]{8,128}$/', $idempotency_key ) ) { return new WP_Error( 'wca_idempotency_required', __( 'A valid 8-128 character idempotency key is required.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n"""
    replace_once(path, old, new)

elif round_no == 8:
    path = 'includes/class-wca-service.php'
    anchor = """\t\t$guardian = WCA_Authorization::guardian_context( $patient_user_id, $guardian_user_id, $actor_user_id );\n\t\tif ( is_wp_error( $guardian ) ) { return $guardian; }\n\t\t$red_flag = self::emergency_red_flag"""
    replacement = """\t\t$guardian = WCA_Authorization::guardian_context( $patient_user_id, $guardian_user_id, $actor_user_id );\n\t\tif ( is_wp_error( $guardian ) ) { return $guardian; }\n\t\t$patient_timezone = isset( $data['timezone'] ) && '' !== trim( (string) $data['timezone'] ) ? (string) $data['timezone'] : SWC_Helpers::user_timezone( $patient_user_id );\n\t\tif ( ! self::valid_timezone( $patient_timezone ) ) { return new WP_Error( 'wca_patient_timezone_invalid', __( 'A valid IANA time zone is required when a patient time zone is supplied.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$red_flag = self::emergency_red_flag"""
    replace_once(path, anchor, replacement)
    replace_once(path, "'patient_timezone'       => self::valid_timezone( $data['timezone'] ?? '' ) ? (string) $data['timezone'] : 'UTC',", "'patient_timezone'       => $patient_timezone,")
    replace_once(path, "function () use ( $patient_user_id, $guardian_user_id, $actor_user_id, $claims, $hold, $service, $clinic, $remote, $data, $idempotency_key, $claim, &$created_appointment_id )", "function () use ( $patient_user_id, $guardian_user_id, $actor_user_id, $claims, $hold, $service, $clinic, $remote, $data, $idempotency_key, $claim, $patient_timezone, &$created_appointment_id )")

elif round_no == 9:
    path = 'includes/class-wca-service.php'
    old = """\t\t$from = self::valid_date( $args['date_from'] ?? '' ) ? (string) $args['date_from'] : gmdate( 'Y-m-d' );\n\t\t$to   = self::valid_date( $args['date_to'] ?? '' ) ? (string) $args['date_to'] : gmdate( 'Y-m-d', time() + 30 * DAY_IN_SECONDS );\n"""
    new = """\t\tif ( isset( $args['date_from'] ) && '' !== (string) $args['date_from'] && ! self::valid_date( $args['date_from'] ) ) { return new WP_Error( 'wca_slot_date_from_invalid', __( 'The slot-search start date is invalid.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\tif ( isset( $args['date_to'] ) && '' !== (string) $args['date_to'] && ! self::valid_date( $args['date_to'] ) ) { return new WP_Error( 'wca_slot_date_to_invalid', __( 'The slot-search end date is invalid.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$from = ! empty( $args['date_from'] ) ? (string) $args['date_from'] : gmdate( 'Y-m-d' );\n\t\t$to   = ! empty( $args['date_to'] ) ? (string) $args['date_to'] : gmdate( 'Y-m-d', time() + 30 * DAY_IN_SECONDS );\n"""
    replace_once(path, old, new)

elif round_no == 10:
    path = 'includes/class-wca-service.php'
    old = """\t\t\t$check = SWC_Helpers::assert_expected( $appointment_id, $expected_status, $expected_version );\n\t\t\tif ( is_wp_error( $check ) ) { return $check; }\n\t\t\t$current = SWC_Helpers::status( $appointment_id );\n"""
    new = """\t\t\t$check = SWC_Helpers::assert_expected( $appointment_id, $expected_status, $expected_version );\n\t\t\tif ( is_wp_error( $check ) ) { return $check; }\n\t\t\t$current_auth = WCA_Authorization::can_transition_appointment( $appointment_id, $next, $actor_user_id );\n\t\t\tif ( is_wp_error( $current_auth ) ) { return $current_auth; }\n\t\t\t$current = SWC_Helpers::status( $appointment_id );\n"""
    replace_once(path, old, new)

elif round_no == 11:
    path = 'includes/class-wca-service.php'
    old = """\t\t\tif ( 'checked_in' === $next ) { update_post_meta( $appointment_id, '_swc_checked_in_at_utc', WCA_Repository::now() ); update_post_meta( $appointment_id, '_swc_actual_mode', sanitize_key( $data['actual_mode'] ?? SWC_Helpers::meta( $appointment_id, 'consultation_type' ) ) ); }\n"""
    new = """\t\t\tif ( 'checked_in' === $next ) {\n\t\t\t\t$actual_mode = sanitize_key( $data['actual_mode'] ?? SWC_Helpers::meta( $appointment_id, 'consultation_type' ) );\n\t\t\t\tif ( ! in_array( $actual_mode, array( 'online', 'in_person', 'hybrid', 'home_visit' ), true ) ) { return new WP_Error( 'wca_actual_mode_invalid', __( 'A valid consultation mode is required for check-in.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t\t\tupdate_post_meta( $appointment_id, '_swc_checked_in_at_utc', WCA_Repository::now() );\n\t\t\t\tupdate_post_meta( $appointment_id, '_swc_actual_mode', $actual_mode );\n\t\t\t}\n"""
    replace_once(path, old, new)

elif round_no == 12:
    path = 'includes/class-wca-rest.php'
    old = """\tprivate static function appointment_projection( $id ) {\n\t\treturn array(\n\t\t\t'public_ref'        => (string) SWC_Helpers::meta( $id, 'public_ref', 'appointment-' . $id ),\n\t\t\t'status'            => SWC_Helpers::status( $id ),\n\t\t\t'version'           => SWC_Helpers::record_version( $id ),\n\t\t\t'scheduled_at_utc'  => (string) SWC_Helpers::meta( $id, 'preferred_at_utc' ),\n\t\t\t'end_at_utc'        => (string) SWC_Helpers::meta( $id, 'appointment_end_utc' ),\n\t\t\t'timezone'          => (string) SWC_Helpers::meta( $id, 'patient_timezone' ),\n\t\t\t'consultation_type' => (string) SWC_Helpers::meta( $id, 'consultation_type' ),\n\t\t\t'clinic_id'         => absint( SWC_Helpers::meta( $id, 'clinic_id' ) ),\n\t\t\t'service_id'        => absint( SWC_Helpers::meta( $id, 'service_id' ) ),\n\t\t\t'allowed_actions'   => WCA_Contracts::allowed_transitions( WCA_Authorization::appointment_actor( $id, get_current_user_id() ), SWC_Helpers::status( $id ) ),\n\t\t\t'clinical_authority'=> false,\n\t\t);\n\t}\n"""
    new = """\tprivate static function appointment_projection( $id ) {\n\t\t$clinic = WCA_Repository::get_clinic( absint( SWC_Helpers::meta( $id, 'clinic_id' ) ), false );\n\t\t$service = WCA_Repository::get_service( absint( SWC_Helpers::meta( $id, 'service_id' ) ), false );\n\t\treturn array(\n\t\t\t'public_ref'        => (string) SWC_Helpers::meta( $id, 'public_ref', 'appointment-' . $id ),\n\t\t\t'status'            => SWC_Helpers::status( $id ),\n\t\t\t'version'           => SWC_Helpers::record_version( $id ),\n\t\t\t'scheduled_at_utc'  => (string) SWC_Helpers::meta( $id, 'preferred_at_utc' ),\n\t\t\t'end_at_utc'        => (string) SWC_Helpers::meta( $id, 'appointment_end_utc' ),\n\t\t\t'timezone'          => (string) SWC_Helpers::meta( $id, 'patient_timezone' ),\n\t\t\t'consultation_type' => (string) SWC_Helpers::meta( $id, 'consultation_type' ),\n\t\t\t'clinic_ref'        => $clinic ? (string) $clinic['public_ref'] : '',\n\t\t\t'service_ref'       => $service ? (string) $service['public_ref'] : '',\n\t\t\t'allowed_actions'   => WCA_Contracts::allowed_transitions( WCA_Authorization::appointment_actor( $id, get_current_user_id() ), SWC_Helpers::status( $id ) ),\n\t\t\t'clinical_authority'=> false,\n\t\t);\n\t}\n\n\tprivate static function protected_mutation_projection( $result, $type ) {\n\t\tif ( is_wp_error( $result ) || ! is_array( $result ) ) { return $result; }\n\t\tif ( 'appointment' === $type ) {\n\t\t\treturn array_intersect_key( $result, array_flip( array( 'public_ref','status','version','trace_id' ) ) );\n\t\t}\n\t\tif ( 'payment' === $type ) {\n\t\t\treturn array_intersect_key( $result, array_flip( array( 'public_ref','status','currency','amount_minor','platform_commission_minor','version','created_at','updated_at' ) ) );\n\t\t}\n\t\tif ( 'complaint' === $type ) {\n\t\t\treturn array_intersect_key( $result, array_flip( array( 'public_ref','category','status','version','created_at','updated_at' ) ) );\n\t\t}\n\t\treturn array();\n\t}\n"""
    replace_once(path, old, new)
    replace_once(path, "return self::respond( WCA_Service::request_appointment( self::data( $request ) ), 201 );", "return self::respond( self::protected_mutation_projection( WCA_Service::request_appointment( self::data( $request ) ), 'appointment' ), 201 );")
    replace_once(path, "return self::respond( WCA_Service::transition_appointment( absint( $request['id'] ), $raw_next, $data ) );", "return self::respond( self::protected_mutation_projection( WCA_Service::transition_appointment( absint( $request['id'] ), $raw_next, $data ), 'appointment' ) );")
    replace_once(path, "return self::respond( WCA_Service::create_payment_intent( absint( $request['id'] ), sanitize_key( $request->get_param( 'provider' ) ?: 'manual' ), get_current_user_id(), trim( (string) $request->get_header( 'Idempotency-Key' ) ) ), 201 );", "return self::respond( self::protected_mutation_projection( WCA_Service::create_payment_intent( absint( $request['id'] ), sanitize_key( $request->get_param( 'provider' ) ?: 'manual' ), get_current_user_id(), trim( (string) $request->get_header( 'Idempotency-Key' ) ) ), 'payment' ), 201 );")
    replace_once(path, "return self::respond( WCA_Service::create_complaint( self::data( $request ) ), 201 );", "return self::respond( self::protected_mutation_projection( WCA_Service::create_complaint( self::data( $request ) ), 'complaint' ), 201 );")

elif round_no == 13:
    path = 'includes/class-wca-service.php'
    old = """\t\t\tforeach ( $appointments as $id ) {\n\t\t\t\t$status = SWC_Helpers::status( $id );\n\t\t\t\tif ( ! WCA_Contracts::is_terminal( $status ) ) {\n\t\t\t\t\tupdate_post_meta( $id, '_swc_doctor_authority_hold', '1' );\n\t\t\t\t\tupdate_post_meta( $id, '_swc_doctor_authority_hold_reason', sanitize_text_field( $reason ) );\n\t\t\t\t\tWCA_Repository::enqueue( 'File19.NotificationRequested.v1', (string) SWC_Helpers::meta( $id, 'public_ref' ), array( 'event' => 'doctor_authority_hold', 'recipients' => array( absint( SWC_Helpers::meta( $id, 'patient_user_id', get_post_field( 'post_author', $id ) ) ) ) ), WCA_Observability::trace_id() );\n\t\t\t\t}\n\t\t\t\t$seen++;\n\t\t\t}\n"""
    new = """\t\t\tforeach ( $appointments as $id ) {\n\t\t\t\t$status = SWC_Helpers::status( $id );\n\t\t\t\tif ( ! WCA_Contracts::is_terminal( $status ) ) {\n\t\t\t\t\t$reconciled = WCA_Repository::transaction( function () use ( $id, $reason ) {\n\t\t\t\t\t\tupdate_post_meta( $id, '_swc_doctor_authority_hold', '1' );\n\t\t\t\t\t\tupdate_post_meta( $id, '_swc_doctor_authority_hold_reason', sanitize_text_field( $reason ) );\n\t\t\t\t\t\tif ( '1' !== (string) get_post_meta( $id, '_swc_doctor_authority_hold', true ) ) { return new WP_Error( 'wca_doctor_hold_persist', __( 'Doctor authority hold could not be persisted safely.', 'worldwide-clinic-appointments' ), array( 'status' => 500 ) ); }\n\t\t\t\t\t\t$queued = WCA_Repository::enqueue( 'File19.NotificationRequested.v1', (string) SWC_Helpers::meta( $id, 'public_ref' ), array( 'event' => 'doctor_authority_hold', 'recipients' => array( absint( SWC_Helpers::meta( $id, 'patient_user_id', get_post_field( 'post_author', $id ) ) ) ), WCA_Observability::trace_id() );\n\t\t\t\t\t\treturn is_wp_error( $queued ) ? $queued : true;\n\t\t\t\t\t}, 'wca_doctor_suspension_reconcile_transaction' );\n\t\t\t\t\tif ( is_wp_error( $reconciled ) ) { WCA_Observability::log( 'error', 'doctor_suspension_reconcile_failed', array( 'appointment_ref' => (string) SWC_Helpers::meta( $id, 'public_ref' ), 'error' => $reconciled->get_error_code() ) ); }\n\t\t\t\t}\n\t\t\t\t$seen++;\n\t\t\t}\n"""
    replace_once(path, old, new)

elif round_no == 14:
    path = 'includes/class-wca-service.php'
    old = """\t\tif ( $service_id ) {\n\t\t\t$current = WCA_Repository::get_service( $service_id, false );\n\t\t\tif ( ! $current || absint( $current['clinic_id'] ) !== absint( $clinic['id'] ) ) { return new WP_Error( 'wca_service_scope', __( 'The service does not belong to this clinic.', 'worldwide-clinic-appointments' ), array( 'status' => 404 ) ); }\n\t\t}\n"""
    new = """\t\t$current = null;\n\t\tif ( $service_id ) {\n\t\t\t$current = WCA_Repository::get_service( $service_id, false );\n\t\t\tif ( ! $current || absint( $current['clinic_id'] ) !== absint( $clinic['id'] ) ) { return new WP_Error( 'wca_service_scope', __( 'The service does not belong to this clinic.', 'worldwide-clinic-appointments' ), array( 'status' => 404 ) ); }\n\t\t}\n\t\t$consultation_type = sanitize_key( $data['consultation_type'] ?? ( $current['consultation_type'] ?? '' ) );\n\t\tif ( ! in_array( $consultation_type, array( 'online', 'in_person', 'hybrid', 'home_visit' ), true ) ) { return new WP_Error( 'wca_service_consultation_type', __( 'A valid consultation type is required.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$currency = strtoupper( preg_replace( '/[^A-Za-z]/', '', (string) ( $data['currency'] ?? ( $current['currency'] ?? '' ) ) ) );\n\t\tif ( ! preg_match( '/^[A-Z]{3}$/', $currency ) ) { return new WP_Error( 'wca_service_currency', __( 'A valid three-letter currency code is required.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$data['consultation_type'] = $consultation_type;\n\t\t$data['currency'] = $currency;\n"""
    replace_once(path, old, new)

elif round_no == 15:
    path = 'includes/class-wca-repository.php'
    # Branch root timezone must not silently normalize.
    replace_once(path, "\t\t$row   = array(\n\t\t\t'public_ref'      => self::uuid(),", "\t\t$timezone = (string) ( $data['timezone'] ?? '' );\n\t\tif ( ! WCA_Service::valid_timezone( $timezone ) ) { return new WP_Error( 'wca_repository_branch_timezone', __( 'Branch persistence requires a valid IANA time zone.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$row   = array(\n\t\t\t'public_ref'      => self::uuid(),")
    replace_once(path, "'timezone'        => WCA_Service::valid_timezone( $data['timezone'] ?? 'UTC' ) ? (string) $data['timezone'] : 'UTC',", "'timezone'        => $timezone,")
    # Service root type/currency must fail closed.
    replace_once(path, "\t\t$currency = strtoupper( preg_replace( '/[^A-Z]/', '', (string) ( $data['currency'] ?? 'PKR' ) ) );\n\t\t$row = array(", "\t\t$currency = strtoupper( preg_replace( '/[^A-Z]/', '', (string) ( $data['currency'] ?? '' ) ) );\n\t\t$consultation_type = sanitize_key( $data['consultation_type'] ?? '' );\n\t\tif ( ! preg_match( '/^[A-Z]{3}$/', $currency ) ) { return new WP_Error( 'wca_repository_service_currency', __( 'Service persistence requires a valid three-letter currency code.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\tif ( ! in_array( $consultation_type, array( 'online', 'in_person', 'hybrid', 'home_visit' ), true ) ) { return new WP_Error( 'wca_repository_service_type', __( 'Service persistence requires a valid consultation type.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$row = array(")
    replace_once(path, "'consultation_type'         => in_array( $data['consultation_type'] ?? '', array( 'online', 'in_person', 'hybrid', 'home_visit' ), true ) ? $data['consultation_type'] : 'online',", "'consultation_type'         => $consultation_type,")
    replace_once(path, "'currency'                  => 3 === strlen( $currency ) ? $currency : 'PKR',", "'currency'                  => $currency,")
    # Availability root timezone must fail closed.
    replace_once(path, "\t\t$table = WCA_Schema::tables()['availability'];\n\t\t$row = array(\n\t\t\t'clinic_id'", "\t\t$table = WCA_Schema::tables()['availability'];\n\t\t$timezone = (string) ( $data['timezone'] ?? '' );\n\t\tif ( ! WCA_Service::valid_timezone( $timezone ) ) { return new WP_Error( 'wca_repository_availability_timezone', __( 'Availability persistence requires a valid IANA time zone.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }\n\t\t$row = array(\n\t\t\t'clinic_id'")
    replace_once(path, "'timezone'       => WCA_Service::valid_timezone( $data['timezone'] ?? '' ) ? (string) $data['timezone'] : 'UTC',", "'timezone'       => $timezone,")

elif round_no == 16:
    # Release identity + permanent regression evidence after all product corrections.
    for path in ['worldwide-clinic.php','includes/class-wca-contracts.php']:
        text = read(path)
        if '1.2.10' not in text:
            raise SystemExit(f'current version anchor missing in {path}')
        write(path, text.replace('1.2.10', '1.2.11'))
    for p in (ROOT / 'tests').glob('*.php'):
        text = p.read_text()
        if '1.2.10' in text:
            p.write_text(text.replace('1.2.10', '1.2.11'))

    test = r'''<?php
/** File 08 eleventh fresh twenty-round corrective regression gate. */
$root=dirname(__DIR__); $failures=array(); $checks=0;
function e11src($p){global $root,$failures;$f=$root.'/'.$p;if(!is_file($f)){$failures[]='Missing '.$p;return '';} $s=file_get_contents($f);return is_string($s)?$s:'';}
function e11has($l,$s,$n){global $failures,$checks;$checks++;if(false===strpos($s,$n)){$failures[]=$l.' missing: '.$n;}}
function e11lacks($l,$s,$n){global $failures,$checks;$checks++;if(false!==strpos($s,$n)){$failures[]=$l.' forbidden: '.$n;}}
$boot=e11src('worldwide-clinic.php');$contracts=e11src('includes/class-wca-contracts.php');$repo=e11src('includes/class-wca-repository.php');$service=e11src('includes/class-wca-service.php');$helpers=e11src('includes/class-swc-helpers.php');$outbox=e11src('includes/class-wca-outbox.php');$rest=e11src('includes/class-wca-rest.php');
foreach(array('$started = $wpdb->query( \'START TRANSACTION\' )','$committed = $wpdb->query( \'COMMIT\' )','_commit') as $n){e11has('repository transaction control',$repo,$n);}foreach(array('swc_transaction_start_failed','swc_transaction_commit_failed') as $n){e11has('appointment transaction control',$helpers,$n);}e11has('stale lock compare-and-swap',$helpers,'option_value=%s WHERE option_name=%s AND option_value=%s');e11lacks('stale lock delete-before-acquire',$helpers,"delete_option( $key );\n\t\t\t\tadd_option");
e11has('worker-fenced complete',$repo,'complete_outbox( $id, $worker');e11has('worker-fenced failure',$repo,'fail_outbox( $id, $error, $attempts, $worker');e11has('dispatcher completion check',$outbox,'durable worker-fenced finalization failed');e11has('dispatcher finalization contention',$outbox,'outbox_finalize_contention_total');e11has('all-recipient fallback',$outbox,'$all_sent = true');e11lacks('partial-recipient success',$outbox,'$sent = wp_mail');
e11has('appointment replay key bounds',$service,"preg_match( '/^[A-Za-z0-9._:-]{8,128}$/', $idempotency_key )");e11has('patient timezone fail closed',$service,'wca_patient_timezone_invalid');e11has('slot from date fail closed',$service,'wca_slot_date_from_invalid');e11has('slot to date fail closed',$service,'wca_slot_date_to_invalid');e11has('inside-lock authorization recheck',$service,'$current_auth = WCA_Authorization::can_transition_appointment');e11has('actual mode validation',$service,'wca_actual_mode_invalid');
e11has('opaque clinic appointment DTO',$rest,"'clinic_ref'");e11has('opaque service appointment DTO',$rest,"'service_ref'");e11has('protected mutation allowlist',$rest,'protected_mutation_projection');e11lacks('appointment DTO native clinic id',$rest,"'clinic_id'         => absint( SWC_Helpers::meta");e11lacks('appointment DTO native service id',$rest,"'service_id'        => absint( SWC_Helpers::meta");e11has('doctor suspension atomic reconciliation',$service,'wca_doctor_suspension_reconcile_transaction');e11has('doctor suspension failure evidence',$service,'doctor_suspension_reconcile_failed');e11has('service type validation',$service,'wca_service_consultation_type');e11has('service currency validation',$service,'wca_service_currency');e11has('repository branch timezone validation',$repo,'wca_repository_branch_timezone');e11has('repository service currency validation',$repo,'wca_repository_service_currency');e11has('repository service type validation',$repo,'wca_repository_service_type');e11has('repository availability timezone validation',$repo,'wca_repository_availability_timezone');e11has('plugin 1.2.11',$boot,'Version: 1.2.11');e11has('runtime 1.2.11',$contracts,"RUNTIME_VERSION                 = '1.2.11'");e11has('schema stays 3.2.0',$contracts,"SCHEMA_VERSION                  = '3.2.0'");
$runtime=implode("\n",array($boot,$contracts,$repo,$service,$helpers,$outbox,$rest));foreach(array('eval(','base64_decode(','shell_exec(','unserialize(') as $n){e11lacks('forbidden runtime primitive',$runtime,$n);}if($failures){fwrite(STDERR,"File 08 eleventh twenty-round regression gate failed:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo 'File 08 eleventh fresh twenty-round regression assertions passed: '.$checks.'/'.$checks.".\n";
'''
    write('tests/eleventh-twenty-review-regressions.php', test)
    runall = read('tests/run-all.php')
    if "'eleventh-twenty-review-regressions.php'" not in runall:
        runall = runall.replace("'tenth-ten-review-regressions.php' );", "'tenth-ten-review-regressions.php', 'eleventh-twenty-review-regressions.php' );")
        if runall == read('tests/run-all.php'):
            raise SystemExit('run-all insertion anchor missing')
        write('tests/run-all.php', runall)

    # Current release docs, preserving historical sections.
    replace_once('README.md', 'Runtime candidate: **1.2.10**', 'Runtime candidate: **1.2.11**')
    append_before('README.md', '\n## Canonical routes\n', "\nThe **eleventh fresh 20-round corrective audit** reviewed the exact v1.2.10 corrected source sequentially. Product defects were corrected before the next round: transaction-control failures now fail closed; resource-lock stale takeover uses compare-and-swap; outbox finalization is worker-fenced and durable; notification fallback requires delivery to every intended recipient; appointment replay keys/time zones/date ranges and check-in mode fail closed; transition authorization is revalidated inside the mutation lock; protected REST DTOs use opaque owner references; doctor-suspension reconciliation is atomic with File19 projection; and service/availability persistence no longer silently normalizes invalid canonical values. R17-R20 then re-reviewed privacy/retention, Future24/cross-file boundaries, migration/security/accessibility/package hygiene, and final plan/ownership parity with no additional supported source defect.\n")
    replace_once('STATUS.md', 'Runtime candidate: **1.2.10**', 'Runtime candidate: **1.2.11**')
    append_before('STATUS.md', '\n## Evidence-state classification\n', "\n## Eleventh fresh 20-round corrective audit\n\nA fresh 20-round sequential review-and-correct cycle was run against exact v1.2.10 source. R1-R15 corrected transaction-control, lock-fencing, outbox finalization, recipient-delivery, request validation, authorization TOCTOU, protected DTO, doctor-suspension reconciliation, and canonical persistence validation gaps. R16 aligned runtime/tests/docs to v1.2.11 and added permanent regression evidence. R17-R20 were fresh corrected-state reviews and found no additional supported repository defect. Core schema remains 3.2.0, continuity 1.1.0, Future24 1.0.0. Repository evidence remains distinct from staging/live evidence.\n")
    readme = read('readme.txt')
    readme = readme.replace('Stable tag: 1.2.10', 'Stable tag: 1.2.11', 1)
    readme = readme.replace('Version 1.2.10 implements', 'Version 1.2.11 implements', 1)
    readme = readme.replace('File 08 v1.2.10 candidate', 'File 08 v1.2.11 candidate', 1)
    marker = '== Changelog ==\n\n'
    entry = "= 1.2.11 =\n* Completed the eleventh fresh sequential 20-round corrective audit.\n* Transaction start/commit failures fail closed in canonical owner and appointment mutations.\n* Stale scheduling lock takeover is compare-and-swap safe; outbox finalization is worker-fenced and durability-aware.\n* Notification fallback requires every intended recipient; appointment replay/timezone/date/check-in validation fails closed.\n* Protected REST mutation/read DTOs use opaque references instead of native database IDs.\n* Doctor suspension reconciliation and required File19 projection are atomic.\n* Service/branch/availability canonical persistence rejects invalid values instead of silent normalization.\n* Runtime 1.2.11; core schema 3.2.0; continuity 1.1.0; Future24 1.0.0. Repository/CI/package evidence remains distinct from staging/live evidence.\n\n"
    if entry not in readme:
        if marker not in readme: raise SystemExit('readme changelog marker missing')
        readme = readme.replace(marker, marker + entry, 1)
    write('readme.txt', readme)
    changelog = read('CHANGELOG.md')
    entry2 = "## 1.2.11 — 2026-08-12\n\n- Completed the eleventh fresh sequential 20-round corrective cycle against exact v1.2.10 source.\n- Fail closed when SQL owner/appointment transactions cannot start or commit.\n- Replaced stale option-lock delete/recreate takeover with compare-and-swap and fenced outbox completion/failure by worker lease.\n- Made dispatcher durable-finalization failures visible and notification fallback all-recipient successful-or-retryable.\n- Hardened appointment replay keys, patient timezone, slot dates, inside-lock authorization, and check-in mode validation.\n- Removed native database IDs from protected appointment/payment/complaint REST response projections.\n- Made doctor-suspension hold + File19 projection atomic and added fail-closed service/branch/availability persistence validation.\n- Runtime 1.2.11; schemas remain core 3.2.0 / continuity 1.1.0 / Future24 1.0.0.\n- R17-R20 fresh corrected-state reviews found no additional supported repository defect; staging/live evidence remains separate.\n\n"
    if entry2 not in changelog:
        changelog = changelog.replace('# Changelog\n\n', '# Changelog\n\n' + entry2, 1)
    write('CHANGELOG.md', changelog)
    evidence = """# File 08 — Eleventh Fresh 20-Round Review Evidence\n\nBaseline source HEAD: `6e7acc0d768e4258e6262d337d409dff3f635533` (v1.2.10).\n\nSequence law: each supported finding was corrected and the full source QA suite was re-run before the next substantive review round.\n\n- E11-R01: canonical repository transaction START/COMMIT failure was unchecked — fixed fail-closed.\n- E11-R02: appointment transaction START/COMMIT failure was unchecked — fixed fail-closed.\n- E11-R03: stale resource-lock takeover used delete/recreate — replaced with compare-and-swap takeover fencing and a longer stale lease.\n- E11-R04: outbox completion/failure lacked worker lease fencing — fixed.\n- E11-R05: dispatcher ignored durable completion/failure finalization results — fixed and instrumented.\n- E11-R06: fallback email could mark multi-recipient notification delivered after only one successful recipient — fixed all-recipient semantics.\n- E11-R07: appointment request replay key was unbounded/noncanonical — fixed 8–128 character contract.\n- E11-R08: explicitly invalid patient timezone silently became UTC — fixed fail-closed with account timezone default only when absent.\n- E11-R09: explicitly invalid slot-search dates silently defaulted — fixed fail-closed.\n- E11-R10: transition authorization was checked before the resource lock only — revalidated inside the locked mutation.\n- E11-R11: check-in actual mode accepted arbitrary sanitized keys — restricted to canonical consultation modes.\n- E11-R12: protected appointment/payment/complaint REST DTOs exposed native database identifiers — replaced with opaque/allowlisted response projections.\n- E11-R13: doctor-suspension hold and File19 notification projection could partially commit and enqueue failure was ignored — made atomic and failure-visible.\n- E11-R14: service mutation silently normalized malformed explicit consultation type/currency — service root now rejects invalid values.\n- E11-R15: repository branch/service/availability persistence still silently normalized invalid canonical values — persistence root now rejects them.\n- E11-R16: release/test/document identity and permanent regression evidence lagged corrected source — advanced to v1.2.11 with no schema inflation.\n- E11-R17: privacy/retention/legal-hold corrected-state review — no additional supported repository defect.\n- E11-R18: Future24/cross-file ownership/concurrency corrected-state review — no additional supported repository defect.\n- E11-R19: migration/security/accessibility/repository-hygiene corrected-state review — no additional supported repository defect.\n- E11-R20: final governing-plan, ownership, package and release-parity review — no additional supported repository defect.\n\nStaging/live/operational acceptance is not established by this repository record.\n"""
    write('ELEVENTH-TWENTY-REVIEW-EVIDENCE.md', evidence)

else:
    raise SystemExit(f'round {round_no} has no patch; review-only rounds are handled by workflow')

print(f'Applied E11-R{round_no:02d}')
