from pathlib import Path
ROOT=Path('.')
def read(p): return (ROOT/p).read_text()
def write(p,s): (ROOT/p).write_text(s)
def once(p,a,b):
 s=read(p); n=s.count(a)
 if n!=1: raise SystemExit(f'{p}: expected 1 got {n}: {a[:100]!r}')
 write(p,s.replace(a,b,1))

p='includes/class-wca-outbox.php'
once(p,"\t\t$locked = (int) $wpdb->get_var( $wpdb->prepare( 'SELECT GET_LOCK(%s,0)', $lock_name ) );\n\t\tif ( 1 !== $locked ) {\n\t\t\tWCA_Observability::metric( 'outbox_worker_contention_total', 1 );\n\t\t\treturn 0;\n\t\t}","\t\t$locked_raw = $wpdb->get_var( $wpdb->prepare( 'SELECT GET_LOCK(%s,0)', $lock_name ) );\n\t\tif ( null === $locked_raw && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_outbox_lock_read_failed', __( 'The outbox dispatcher lock could not be verified safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\t$locked = (int) $locked_raw;\n\t\tif ( 1 !== $locked ) {\n\t\t\tWCA_Observability::metric( 'outbox_worker_contention_total', 1 );\n\t\t\treturn 0;\n\t\t}")
once(p,"\t\t\t$recovered = WCA_Repository::recover_stale_outbox( 300 );\n\t\t\tif ( $recovered > 0 ) { WCA_Observability::metric( 'outbox_stale_recovered_total', $recovered ); }\n\t\t\t$worker = 'wp-' . substr( hash( 'sha256', wp_generate_uuid4() ), 0, 16 );\n\t\t\t$items  = WCA_Repository::claim_outbox( min( 100, max( 1, absint( $limit ) ) ), $worker );\n\t\t\tforeach ( $items as $item ) {","\t\t\t$recovered = WCA_Repository::recover_stale_outbox( 300 );\n\t\t\tif ( is_wp_error( $recovered ) ) { return $recovered; }\n\t\t\tif ( $recovered > 0 ) { WCA_Observability::metric( 'outbox_stale_recovered_total', $recovered ); }\n\t\t\t$worker = 'wp-' . substr( hash( 'sha256', wp_generate_uuid4() ), 0, 16 );\n\t\t\t$items  = WCA_Repository::claim_outbox( min( 100, max( 1, absint( $limit ) ) ), $worker );\n\t\t\tif ( is_wp_error( $items ) ) { return $items; }\n\t\t\tforeach ( $items as $item ) {")
once(p,"\t\tself::process( self::BATCH_SIZE );\n\t\tWCA_Observability::health();","\t\t$processed = self::process( self::BATCH_SIZE );\n\t\tif ( is_wp_error( $processed ) ) { $errors[] = $processed->get_error_code(); WCA_Observability::log( 'error', 'outbox_process_failed', array( 'error_code' => $processed->get_error_code() ) ); }\n\t\tWCA_Observability::health();")

p='includes/class-wca-repository.php'
once(p,"\t\treturn (int) $wpdb->query( $wpdb->prepare(\n\t\t\t\"UPDATE {$table}","\t\t$updated = $wpdb->query( $wpdb->prepare(\n\t\t\t\"UPDATE {$table}")
# close recover query occurrence uniquely using trailing comment before next doc.
once(p,"\t\t) ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared\n\t}\n\n\t/** @return array<int,array<string,mixed>> */\n\tpublic static function claim_outbox","\t\t) ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared\n\t\tif ( false === $updated ) { return new WP_Error( 'wca_outbox_recovery_failed', __( 'Abandoned outbox leases could not be reconciled safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\treturn (int) $updated;\n\t}\n\n\t/** @return array<int,array<string,mixed>>|WP_Error */\n\tpublic static function claim_outbox")
once(p,"\t\t$ids = (array) $wpdb->get_col( $wpdb->prepare( \"SELECT id FROM {$table} WHERE status IN ('pending','retry') AND next_attempt_at<=%s AND (locked_at IS NULL OR locked_at<%s) ORDER BY id ASC LIMIT %d\", $now, $stale_before, $limit ) );\n\t\t$claimed = array();","\t\t$ids_raw = $wpdb->get_col( $wpdb->prepare( \"SELECT id FROM {$table} WHERE status IN ('pending','retry') AND next_attempt_at<=%s AND (locked_at IS NULL OR locked_at<%s) ORDER BY id ASC LIMIT %d\", $now, $stale_before, $limit ) );\n\t\tif ( null === $ids_raw && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_outbox_claim_read_failed', __( 'Pending outbox work could not be read safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\t$ids = (array) $ids_raw;\n\t\t$claimed = array();")
once(p,"\t\t\t\t$row = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE id=%d AND status='processing' AND locked_by=%s LIMIT 1\", absint( $id ), $worker ), ARRAY_A );\n\t\t\t\tif ( $row ) { $row['payload'] = self::decode( $row['payload_json'] ); unset( $row['payload_json'] ); $claimed[] = $row; }","\t\t\t\t$row = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE id=%d AND status='processing' AND locked_by=%s LIMIT 1\", absint( $id ), $worker ), ARRAY_A );\n\t\t\t\tif ( null === $row && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_outbox_claim_readback_failed', __( 'Claimed outbox work could not be verified safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\t\t\tif ( $row ) { $row['payload'] = self::decode( $row['payload_json'] ); unset( $row['payload_json'] ); $claimed[] = $row; }")
once(p,"\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE scope=%s AND key_hash=%s AND actor_user_id=%d LIMIT 1\", $scope, $key_hash, absint( $actor_user_id ) ), ARRAY_A );\n\t\tif ( $existing ) {","\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE scope=%s AND key_hash=%s AND actor_user_id=%d LIMIT 1\", $scope, $key_hash, absint( $actor_user_id ) ), ARRAY_A );\n\t\tif ( null === $existing && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_idempotency_claim_read_failed', __( 'Current idempotency state could not be read safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\tif ( $existing ) {")
once(p,"\t\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE scope=%s AND key_hash=%s AND actor_user_id=%d LIMIT 1\", $scope, $key_hash, absint( $actor_user_id ) ), ARRAY_A );\n\t\t\tif ( $existing && hash_equals","\t\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE scope=%s AND key_hash=%s AND actor_user_id=%d LIMIT 1\", $scope, $key_hash, absint( $actor_user_id ) ), ARRAY_A );\n\t\t\tif ( null === $existing && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_idempotency_race_read_failed', __( 'Concurrent idempotency state could not be reconciled safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\t\tif ( $existing && hash_equals")
once(p,"\t\t$row = $wpdb->get_row( $wpdb->prepare( \"SELECT status,response_code,response_json,updated_at,expires_at FROM {$table} WHERE scope=%s AND key_hash=%s AND actor_user_id=%d LIMIT 1\", $scope, $key_hash, absint( $actor_user_id ) ), ARRAY_A );\n\t\tif ( ! $row ) { return new WP_Error( 'wca_idempotency_not_found'","\t\t$row = $wpdb->get_row( $wpdb->prepare( \"SELECT status,response_code,response_json,updated_at,expires_at FROM {$table} WHERE scope=%s AND key_hash=%s AND actor_user_id=%d LIMIT 1\", $scope, $key_hash, absint( $actor_user_id ) ), ARRAY_A );\n\t\tif ( null === $row && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_idempotency_status_read_failed', __( 'Mutation reconciliation state could not be read safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\tif ( ! $row ) { return new WP_Error( 'wca_idempotency_not_found'")
# Payment intent idempotency reads are also authoritative.
once(p,"\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE appointment_id=%d AND provider=%s AND request_key=%s LIMIT 1\", $appointment_id, $provider, $request_key ), ARRAY_A );\n\t\tif ( $existing ) { return $existing; }","\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE appointment_id=%d AND provider=%s AND request_key=%s LIMIT 1\", $appointment_id, $provider, $request_key ), ARRAY_A );\n\t\tif ( null === $existing && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_payment_replay_read_failed', __( 'Current payment-intent replay state could not be read safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\tif ( $existing ) { return $existing; }")
once(p,"\t\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE appointment_id=%d AND provider=%s AND request_key=%s LIMIT 1\", $appointment_id, $provider, $request_key ), ARRAY_A );\n\t\t\tif ( $existing ) { return $existing; }","\t\t\t$existing = $wpdb->get_row( $wpdb->prepare( \"SELECT * FROM {$table} WHERE appointment_id=%d AND provider=%s AND request_key=%s LIMIT 1\", $appointment_id, $provider, $request_key ), ARRAY_A );\n\t\t\tif ( null === $existing && '' !== (string) $wpdb->last_error ) { return new WP_Error( 'wca_payment_race_read_failed', __( 'Concurrent payment-intent state could not be reconciled safely.', 'worldwide-clinic-appointments' ), array( 'status' => 503 ) ); }\n\t\t\tif ( $existing ) { return $existing; }")

p='tests/fifteenth-twenty-review-regressions.php'; s=read(p)
insert="""
t15h('R3 dispatcher lock read failure','includes/class-wca-outbox.php','wca_outbox_lock_read_failed');
t15h('R3 stale outbox recovery failure','includes/class-wca-repository.php','wca_outbox_recovery_failed');
t15h('R3 outbox claim read failure','includes/class-wca-repository.php','wca_outbox_claim_read_failed');
t15h('R3 outbox readback failure','includes/class-wca-repository.php','wca_outbox_claim_readback_failed');
t15h('R3 idempotency initial read failure','includes/class-wca-repository.php','wca_idempotency_claim_read_failed');
t15h('R3 idempotency race read failure','includes/class-wca-repository.php','wca_idempotency_race_read_failed');
t15h('R3 idempotency status read failure','includes/class-wca-repository.php','wca_idempotency_status_read_failed');
t15h('R3 payment replay read failure','includes/class-wca-repository.php','wca_payment_replay_read_failed');
"""
marker="if($fail){fwrite(STDERR,\"T15 regression gate failed:"
if marker not in s: raise SystemExit('gate marker missing')
write(p,s.replace(marker,insert+marker,1))
p='FIFTEENTH-TWENTY-REVIEW-EVIDENCE.md'; s=read(p); s += """

## R3 — complete outbox / idempotency / maintenance review

R3 was completed against the R2-corrected state before any R3 correction. It found failure-visibility gaps in advisory lock acquisition, abandoned-outbox recovery, pending-claim/readback, payment/idempotency replay reads, and the authoritative reconciliation query. Database errors could be flattened into contention, no work, or not-found states. The post-review batch makes those reads and recovery operations explicit fail-closed errors and propagates outbox processing failures into maintenance.

R3 result: **SUPPORTED DEFECTS FOUND — corrected together after review completion; full retest required before R4.**
"""; write(p,s)
