from pathlib import Path

p=Path('tools/t16-r1-fix.py')
s=p.read_text()
old='''once(p,\n"\\t\\t$table = self::future24_table();\\n\\t\\tif ( $table ) {",\n"\\t\\t$table = self::future24_table();\\n\\t\\tif ( is_wp_error( $table ) ) { return $table; }\\n\\t\\tif ( $table ) {"\n)\n# second caller is erasure: fail incomplete, do not silently skip.\ns=read(p)\nneedle="\\t\\t$table = self::future24_table();\\n\\t\\tif ( $table ) {"\nidx=s.find(needle)\nif idx<0: raise SystemExit('wca-privacy: erasure Future24 caller not found after export replacement')\ns=s[:idx]+s[idx:].replace(needle,"\\t\\t$table = self::future24_table();\\n\\t\\tif ( is_wp_error( $table ) ) { $messages[] = __( 'Future24 privacy storage could not be verified safely and will retry.', 'worldwide-clinic-appointments' ); $done = false; $table = ''; }\\n\\t\\tif ( $table ) {",1)\nwrite(p,s)\n# retention caller.\ns=read(p)\nidx=s.rfind(needle)\nif idx<0: raise SystemExit('wca-privacy: retention Future24 caller not found')\ns=s[:idx]+s[idx:].replace(needle,"\\t\\t$table = self::future24_table();\\n\\t\\tif ( is_wp_error( $table ) ) { return $table; }\\n\\t\\tif ( $table ) {",1)\nwrite(p,s)'''
new='''s=read(p)\nneedle="\\t\\t$table = self::future24_table();\\n\\t\\tif ( $table ) {"\nif s.count(needle) != 3: raise SystemExit(f'wca-privacy: expected 3 Future24 callers, got {s.count(needle)}')\ns=s.replace(needle,"\\t\\t$table = self::future24_table();\\n\\t\\tif ( is_wp_error( $table ) ) { return $table; }\\n\\t\\tif ( $table ) {",1)\ns=s.replace(needle,"\\t\\t$table = self::future24_table();\\n\\t\\tif ( is_wp_error( $table ) ) { $messages[] = __( 'Future24 privacy storage could not be verified safely and will retry.', 'worldwide-clinic-appointments' ); $done = false; $table = ''; }\\n\\t\\tif ( $table ) {",1)\ns=s.replace(needle,"\\t\\t$table = self::future24_table();\\n\\t\\tif ( is_wp_error( $table ) ) { return $table; }\\n\\t\\tif ( $table ) {",1)\nwrite(p,s)'''
if old not in s: raise SystemExit('correction script target block not found')
p.write_text(s.replace(old,new,1))
exec(compile(p.read_text(), str(p), 'exec'))
