from pathlib import Path

def one(path,a,b):
 p=Path(path); s=p.read_text();
 if s.count(a)!=1: raise SystemExit(f'{path}: expected one anchor, got {s.count(a)}: {a[:60]}')
 p.write_text(s.replace(a,b,1))

S='includes/class-wca-service.php'
one(S,"\t\treturn (int) $validated;\n\t}\n\n\t/** @return array<string,mixed> */\n\tpublic static function sanitize_rrule", "\t\treturn (int) $validated;\n\t}\n\n\tpublic static function strict_id( $value, $allow_zero = false ) {\n\t\tif ( $allow_zero && in_array( $value, array( null, '', 0, '0' ), true ) ) { return 0; }\n\t\treturn self::strict_int( $value, 1, PHP_INT_MAX );\n\t}\n\n\t/** @return array<string,mixed> */\n\tpublic static function sanitize_rrule")
for name,code in [('submit_clinic_for_review','wca_clinic_review_identifier'),('activate_clinic','wca_clinic_activate_identifier')]:
 a=f"\tpublic static function {name}( $clinic_id, $expected_version, $actor_user_id = 0 ) {{\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n"
 b=a+f"\t\t$clinic_id = self::strict_id( $clinic_id ); $expected_version = self::strict_id( $expected_version );\n\t\tif ( null === $clinic_id || null === $expected_version ) {{ return new WP_Error( '{code}', __( 'Identifier and expected version must be positive integers.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }}\n"
 one(S,a,b)
one(S,"\tpublic static function create_branch( $data, $actor_user_id = 0 ) {\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n\t\t$clinic = WCA_Repository::get_clinic( absint( $data['clinic_id'] ?? 0 ), false );", "\tpublic static function create_branch( $data, $actor_user_id = 0 ) {\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n\t\t$clinic_id = self::strict_id( $data['clinic_id'] ?? null ); if ( null === $clinic_id ) { return new WP_Error( 'wca_branch_clinic_identifier', __( 'Clinic identifier must be a positive integer.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); } $data['clinic_id'] = $clinic_id;\n\t\t$clinic = WCA_Repository::get_clinic( $clinic_id, false );")
one(S,"\tpublic static function save_service( $data, $service_id = 0, $expected_version = 0, $actor_user_id = 0 ) {\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n\t\t$clinic = WCA_Repository::get_clinic( absint( $data['clinic_id'] ?? 0 ), false );", "\tpublic static function save_service( $data, $service_id = 0, $expected_version = 0, $actor_user_id = 0 ) {\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n\t\t$clinic_id=self::strict_id($data['clinic_id']??null); $service_id=self::strict_id($service_id,true); $expected_version=self::strict_id($expected_version,true);\n\t\tif(null===$clinic_id||null===$service_id||null===$expected_version||($service_id&&!$expected_version)||(!$service_id&&$expected_version)){return new WP_Error('wca_service_identifier',__('Service identifiers and expected version are invalid.','worldwide-clinic-appointments'),array('status'=>400));} $data['clinic_id']=$clinic_id;\n\t\t$clinic = WCA_Repository::get_clinic( $clinic_id, false );")
one(S,"\tpublic static function set_availability( $data, $rule_id = 0, $expected_version = 0, $actor_user_id = 0 ) {\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n\t\t$clinic = WCA_Repository::get_clinic( absint( $data['clinic_id'] ?? 0 ), false );", "\tpublic static function set_availability( $data, $rule_id = 0, $expected_version = 0, $actor_user_id = 0 ) {\n\t\t$actor_user_id = absint( $actor_user_id ?: get_current_user_id() );\n\t\t$clinic_id=self::strict_id($data['clinic_id']??null); $rule_id=self::strict_id($rule_id,true); $expected_version=self::strict_id($expected_version,true);\n\t\tif(null===$clinic_id||null===$rule_id||null===$expected_version||($rule_id&&!$expected_version)||(!$rule_id&&$expected_version)){return new WP_Error('wca_availability_identifier',__('Availability identifiers and expected version are invalid.','worldwide-clinic-appointments'),array('status'=>400));} $data['clinic_id']=$clinic_id;\n\t\t$clinic = WCA_Repository::get_clinic( $clinic_id, false );")
one(S,"\t\tif ( empty( $data['expected_status'] ) || ! isset( $data['expected_version'] ) || absint( $data['expected_version'] ) < 1 ) {\n\t\t\treturn new WP_Error( 'wca_transition_precondition_required', __( 'Current appointment status and positive record version are required.', 'worldwide-clinic-appointments' ), array( 'status' => 409 ) );\n\t\t}", "\t\t$expected_version = isset( $data['expected_version'] ) ? self::strict_id( $data['expected_version'] ) : null;\n\t\tif ( empty( $data['expected_status'] ) || null === $expected_version ) {\n\t\t\treturn new WP_Error( 'wca_transition_precondition_required', __( 'Current appointment status and positive integer record version are required.', 'worldwide-clinic-appointments' ), array( 'status' => 409 ) );\n\t\t}")
one(S,"\t\t$expected_status  = WCA_Contracts::normalize_appointment_status( $raw_expected_status );\n\t\t$expected_version = absint( $data['expected_version'] );", "\t\t$expected_status  = WCA_Contracts::normalize_appointment_status( $raw_expected_status );")
p=Path(S); s=p.read_text();
s=s.replace("$patient_user_id = absint( $data['patient_user_id'] ?? $actor_user_id );", "$patient_user_id = array_key_exists( 'patient_user_id', $data ) ? self::strict_id( $data['patient_user_id'] ) : $actor_user_id; if ( null === $patient_user_id ) { return new WP_Error( 'wca_patient_identifier', __( 'Patient identifier must be a positive integer.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }",2)
s=s.replace("$guardian_user_id = absint( $data['guardian_user_id'] ?? 0 );", "$guardian_user_id = array_key_exists( 'guardian_user_id', $data ) ? self::strict_id( $data['guardian_user_id'], true ) : 0; if ( null === $guardian_user_id ) { return new WP_Error( 'wca_guardian_identifier', __( 'Guardian identifier must be a non-negative integer.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }",1)
s=s.replace("$guardian_user_id= absint( $data['guardian_user_id'] ?? 0 );", "$guardian_user_id = array_key_exists( 'guardian_user_id', $data ) ? self::strict_id( $data['guardian_user_id'], true ) : 0; if ( null === $guardian_user_id ) { return new WP_Error( 'wca_guardian_identifier', __( 'Guardian identifier must be a non-negative integer.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }",1)
p.write_text(s)
one(S,"\t\t$appointment_id = absint( $data['appointment_id'] ?? 0 );", "\t\t$appointment_id = array_key_exists( 'appointment_id', $data ) ? self::strict_id( $data['appointment_id'], true ) : 0; if ( null === $appointment_id ) { return new WP_Error( 'wca_complaint_appointment_identifier', __( 'Appointment identifier must be a non-negative integer.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }")
one(S,"$clinic_id=absint($data['clinic_id'] ?? 0); if(!$clinic_id){return new WP_Error('wca_complaint_scope'", "$clinic_id=self::strict_id($data['clinic_id'] ?? null); if(null===$clinic_id){return new WP_Error('wca_complaint_scope'")
one(S,"\tpublic static function appeal_complaint( $ref, $expected_version, $actor_user_id=0 ) {\n\t\t$actor_user_id=", "\tpublic static function appeal_complaint( $ref, $expected_version, $actor_user_id=0 ) {\n\t\t$expected_version=self::strict_id($expected_version); if(null===$expected_version){return new WP_Error('wca_complaint_expected_version',__('Complaint expected version must be a positive integer.','worldwide-clinic-appointments'),array('status'=>400));}\n\t\t$actor_user_id=")
one(S,"$expected=absint($event['expected_version']??0); if(!preg_match", "$expected=self::strict_id($event['expected_version']??null); if(!preg_match")
one(S,"||!isset(WCA_Contracts::complaint_transition_matrix()[$next])||!$expected){return new WP_Error('wca_cf02_case_event_invalid'", "||!isset(WCA_Contracts::complaint_transition_matrix()[$next])||null===$expected){return new WP_Error('wca_cf02_case_event_invalid'")
R='includes/class-wca-rest.php'
for a,b in [("absint( $request->get_param( 'expected_version' ) )","$request->get_param( 'expected_version' )"),("absint( $data['service_id'] ?? 0 ), absint( $data['expected_version'] ?? 0 )","$data['service_id'] ?? 0, $data['expected_version'] ?? 0"),("absint( $data['rule_id'] ?? 0 ), absint( $data['expected_version'] ?? 0 )","$data['rule_id'] ?? 0, $data['expected_version'] ?? 0"),("absint($data['expected_version']??0),get_current_user_id()","$data['expected_version']??null,get_current_user_id()")]:
 p=Path(R); s=p.read_text();
 if a not in s: raise SystemExit('REST anchor missing '+a)
 p.write_text(s.replace(a,b))
O='includes/class-wca-opaque-api.php'; p=Path(O); s=p.read_text(); s=s.replace("absint( $request->get_param( 'expected_version' ) )","$request->get_param( 'expected_version' )"); p.write_text(s)
F='includes/class-wca-future24.php'
one(F,"\t/** Resolve patient/guardian scheduling intent and recheck File 00 age/guardian truth. */\n\tprivate static function patient_context", "\tprivate static function input_id( $data, $key, $required = true, $default = 0 ) {\n\t\tif ( ! is_array( $data ) || ! array_key_exists( $key, $data ) ) { return $required ? new WP_Error( 'wca_future24_identifier', __( 'A required integer identifier is missing.', 'worldwide-clinic-appointments' ), array( 'status' => 400, 'field' => $key ) ) : $default; }\n\t\tif ( ! $required && in_array( $data[ $key ], array( null, '', 0, '0' ), true ) ) { return 0; }\n\t\t$id=WCA_Service::strict_id($data[$key]); return null===$id ? new WP_Error('wca_future24_identifier',__('Object identifiers must be positive integers.','worldwide-clinic-appointments'),array('status'=>400,'field'=>$key)) : $id;\n\t}\n\n\t/** Resolve patient/guardian scheduling intent and recheck File 00 age/guardian truth. */\n\tprivate static function patient_context")
one(F,"\t\t$patient_id  = absint( isset( $data['patient_user_id'] ) ? $data['patient_user_id'] : $actor );\n\t\t$guardian_id = absint( isset( $data['guardian_user_id'] ) ? $data['guardian_user_id'] : 0 );", "\t\t$patient_id=array_key_exists('patient_user_id',$data)?self::input_id($data,'patient_user_id'):$actor; if(is_wp_error($patient_id)){return $patient_id;}\n\t\t$guardian_id=array_key_exists('guardian_user_id',$data)?self::input_id($data,'guardian_user_id',false,0):0; if(is_wp_error($guardian_id)){return $guardian_id;}")
p=Path(F); s=p.read_text();
for needle in ["\t\t$clinic_id = absint( isset( $data['clinic_id'] ) ? $data['clinic_id'] : 0 );","\t\t$clinic_id = absint( $data['clinic_id'] ?? 0 );"]:
 while needle in s: s=s.replace(needle,"\t\t$clinic_id=self::input_id($data,'clinic_id'); if(is_wp_error($clinic_id)){return $clinic_id;}",1)
p.write_text(s)
one(F,"\t\t\tif ( ! is_array( $window ) ) { continue; }", "\t\t\tif ( ! is_array( $window ) ) { return new WP_Error( 'wca_windows_member_invalid', __( 'Every scheduling window must be a structured start/end object.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }")
one(F,"\t\t\tif ( $start && $end && $end > $start && $start_ts >= $now - 5 * MINUTE_IN_SECONDS && $end_ts > $now && $start_ts <= $now + 180 * DAY_IN_SECONDS && $end_ts - $start_ts <= 14 * DAY_IN_SECONDS ) {\n\t\t\t\t$windows[] = $start . '/' . $end;\n\t\t\t\t$latest_end = max( $latest_end, $end_ts );\n\t\t\t}\n", "\t\t\tif(!$start||!$end||$end<=$start||$start_ts<$now-5*MINUTE_IN_SECONDS||$end_ts<=$now||$start_ts>$now+180*DAY_IN_SECONDS||$end_ts-$start_ts>14*DAY_IN_SECONDS){return new WP_Error('wca_windows_member_invalid',__('Every scheduling window must be valid and within the supported horizon.','worldwide-clinic-appointments'),array('status'=>400));}\n\t\t\t$windows[]=$start.'/'.$end; $latest_end=max($latest_end,$end_ts);\n")
one(F,"\t\t$fields = array_values( array_intersect( array_map( 'sanitize_key', (array) ( $data['fields'] ?? array() ) ), $allowed ) );\n\t\tif ( ! $fields ) { return new WP_Error( 'wca_questionnaire_fields', __( 'At least one approved secure intake field is required.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }", "\t\t$raw_fields=$data['fields']??null; if(!is_array($raw_fields)||!$raw_fields){return new WP_Error('wca_questionnaire_fields',__('At least one approved secure intake field is required.','worldwide-clinic-appointments'),array('status'=>400));}\n\t\t$fields=array(); foreach($raw_fields as $field){if(!is_scalar($field)){return new WP_Error('wca_questionnaire_field_invalid',__('Questionnaire fields must be approved identifiers.','worldwide-clinic-appointments'),array('status'=>400));}$key=sanitize_key((string)$field);if(!in_array($key,$allowed,true)||in_array($key,$fields,true)){return new WP_Error('wca_questionnaire_field_invalid',__('Questionnaire contains an unsupported or duplicate field.','worldwide-clinic-appointments'),array('status'=>400));}$fields[]=$key;}")
one(F,"\t\t\tif ( ! is_array( $item ) ) { continue; }", "\t\t\tif ( ! is_array( $item ) ) { return new WP_Error( 'wca_prerequisite_rule_invalid', __( 'Every prerequisite rule must be a structured object.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }")
one(F,"\t\t\tif ( ! $label ) { continue; }", "\t\t\tif ( ! $label ) { return new WP_Error( 'wca_prerequisite_rule_invalid', __( 'Each prerequisite rule requires a label.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }")
one(F,"\t\t\tif ( ! in_array( $behavior, array( 'provisional','block' ), true ) ) { $behavior = 'provisional'; }", "\t\t\tif ( ! in_array( $behavior, array( 'provisional','block' ), true ) ) { return new WP_Error( 'wca_prerequisite_behavior_invalid', __( 'Prerequisite missing behavior must be provisional or block.', 'worldwide-clinic-appointments' ), array( 'status' => 400 ) ); }")
print('T17 R2 corrections applied')
